-- ============================================================================
-- FindMaxxing demo seed. GENERATED by scripts/generate-seed-sql.ts — do not edit.
-- All people, places and events are fictional. Demo password: "findmaxxing".
-- ============================================================================

-- Vocabulary
insert into public.categories (slug, label, emoji, color, scope, sort_order) values
  ('pickup-sports', 'Pickup sports', '⚽', '#1f8a5b', 'both', 0),
  ('sports-bar', 'Sports bar', '📺', '#ff4d2e', 'place', 1),
  ('watch-party', 'Watch party', '🏈', '#ff4d2e', 'event', 2),
  ('outdoors', 'Outdoors', '🌲', '#2f7d4f', 'both', 3),
  ('fitness', 'Fitness', '🧗', '#0e8f8a', 'both', 4),
  ('food', 'Food', '🌮', '#e0741f', 'both', 5),
  ('coffee-study', 'Coffee & study', '☕', '#8b5a2b', 'both', 6),
  ('nightlife', 'Nightlife', '🌙', '#6b4cff', 'both', 7),
  ('music', 'Music', '🎸', '#c0399b', 'both', 8),
  ('arts', 'Arts', '🎨', '#d1436b', 'both', 9),
  ('gaming-hobby', 'Gaming & hobbies', '🎲', '#3b6fd6', 'both', 10),
  ('date-spot', 'Date spot', '💛', '#e8a600', 'place', 11),
  ('community', 'Community', '🤝', '#4c8ac9', 'both', 12),
  ('college', 'College life', '🎓', '#b13a3a', 'both', 13),
  ('other', 'Other', '📍', '#7b7c85', 'both', 14)
on conflict (slug) do update set label = excluded.label, emoji = excluded.emoji, color = excluded.color, scope = excluded.scope, sort_order = excluded.sort_order;

insert into public.interests (slug, label, emoji, sort_order) values
  ('sports', 'Sports', '🏀', 0),
  ('pickup-sports', 'Pickup games', '⚽', 1),
  ('fitness', 'Fitness', '💪', 2),
  ('hiking', 'Hiking', '🥾', 3),
  ('outdoors', 'Outdoors', '🏕️', 4),
  ('food', 'Food', '🍜', 5),
  ('coffee', 'Coffee', '☕', 6),
  ('studying', 'Studying', '📚', 7),
  ('nightlife', 'Nightlife', '🪩', 8),
  ('music', 'Music', '🎶', 9),
  ('art', 'Art', '🖌️', 10),
  ('gaming', 'Gaming', '🎮', 11),
  ('board-games', 'Board games', '🎲', 12),
  ('climbing', 'Climbing', '🧗', 13),
  ('running', 'Running', '🏃', 14),
  ('cycling', 'Cycling', '🚴', 15),
  ('ohio-state', 'Ohio State', '🌰', 16),
  ('college', 'College', '🎓', 17),
  ('cheap-eats', 'Cheap eats', '🪙', 18),
  ('date-night', 'Date night', '💛', 19),
  ('dogs', 'Dogs', '🐶', 20),
  ('volunteering', 'Volunteering', '🤝', 21),
  ('new-in-town', 'New in town', '🧳', 22),
  ('social', 'Social', '👋', 23)
on conflict (slug) do update set label = excluded.label, emoji = excluded.emoji, sort_order = excluded.sort_order;

-- Demo auth users (the profiles trigger creates matching profile rows)
insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at)
values ('28300d2a-8dcf-4599-a2da-9c4bbcd955da', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'maya@example.com', crypt('findmaxxing', gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{"username":"maya_r","display_name":"Maya Reyes"}', now(), now())
on conflict (id) do nothing;
insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at)
values ('3eb1d493-2346-45eb-ac2f-e4ea355f946a', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'theo@example.com', crypt('findmaxxing', gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{"username":"theo","display_name":"Theo Okafor"}', now(), now())
on conflict (id) do nothing;
insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at)
values ('f097e035-c64b-499d-a203-345d923f934d', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'jules@example.com', crypt('findmaxxing', gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{"username":"jules","display_name":"Jules Park"}', now(), now())
on conflict (id) do nothing;
insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at)
values ('1841f2ef-9435-49e0-ab03-f1e4c6744209', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'sam@example.com', crypt('findmaxxing', gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{"username":"sam_k","display_name":"Sam Kowalski"}', now(), now())
on conflict (id) do nothing;
insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at)
values ('28572a41-206d-4bd8-a853-31ab1a437aea', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'priya@example.com', crypt('findmaxxing', gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{"username":"priya","display_name":"Priya Natarajan"}', now(), now())
on conflict (id) do nothing;
insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at)
values ('b2431795-ed35-49ac-a89b-74286bd6feeb', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'dev@example.com', crypt('findmaxxing', gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{"username":"dev","display_name":"Devin Hale"}', now(), now())
on conflict (id) do nothing;
insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at)
values ('ee4edfe3-9370-441b-a004-14b4bfff0b9d', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'lena@example.com', crypt('findmaxxing', gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{"username":"lena","display_name":"Lena Fischer"}', now(), now())
on conflict (id) do nothing;
insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at)
values ('f6e4d056-f565-41b4-a2e0-f9347bbf87df', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'marcus@example.com', crypt('findmaxxing', gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{"username":"marcus","display_name":"Marcus Bell"}', now(), now())
on conflict (id) do nothing;
insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at)
values ('b12fb965-a620-40e9-a0a8-8d379dcbbf40', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'nina@example.com', crypt('findmaxxing', gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', '{"username":"nina","display_name":"Nina Alvarez"}', now(), now())
on conflict (id) do nothing;

-- Profile details
update public.profiles set bio = 'Moved here in June. Collecting pickup games and cheap tacos.', home_city = 'Columbus', display_name = 'Maya Reyes', username = 'maya_r' where id = '28300d2a-8dcf-4599-a2da-9c4bbcd955da';
insert into public.profile_interests (profile_id, interest_slug) values ('28300d2a-8dcf-4599-a2da-9c4bbcd955da', 'pickup-sports') on conflict do nothing;
insert into public.profile_interests (profile_id, interest_slug) values ('28300d2a-8dcf-4599-a2da-9c4bbcd955da', 'food') on conflict do nothing;
insert into public.profile_interests (profile_id, interest_slug) values ('28300d2a-8dcf-4599-a2da-9c4bbcd955da', 'cheap-eats') on conflict do nothing;
insert into public.profile_interests (profile_id, interest_slug) values ('28300d2a-8dcf-4599-a2da-9c4bbcd955da', 'new-in-town') on conflict do nothing;
insert into public.profile_interests (profile_id, interest_slug) values ('28300d2a-8dcf-4599-a2da-9c4bbcd955da', 'running') on conflict do nothing;
update public.profiles set bio = 'Lifelong Columbus. Will argue about the best place to watch the game.', home_city = 'Columbus', display_name = 'Theo Okafor', username = 'theo' where id = '3eb1d493-2346-45eb-ac2f-e4ea355f946a';
insert into public.profile_interests (profile_id, interest_slug) values ('3eb1d493-2346-45eb-ac2f-e4ea355f946a', 'sports') on conflict do nothing;
insert into public.profile_interests (profile_id, interest_slug) values ('3eb1d493-2346-45eb-ac2f-e4ea355f946a', 'ohio-state') on conflict do nothing;
insert into public.profile_interests (profile_id, interest_slug) values ('3eb1d493-2346-45eb-ac2f-e4ea355f946a', 'nightlife') on conflict do nothing;
insert into public.profile_interests (profile_id, interest_slug) values ('3eb1d493-2346-45eb-ac2f-e4ea355f946a', 'social') on conflict do nothing;
update public.profiles set bio = 'Grad student. Study spots, trails, and the occasional basement show.', home_city = 'Columbus', display_name = 'Jules Park', username = 'jules' where id = 'f097e035-c64b-499d-a203-345d923f934d';
insert into public.profile_interests (profile_id, interest_slug) values ('f097e035-c64b-499d-a203-345d923f934d', 'studying') on conflict do nothing;
insert into public.profile_interests (profile_id, interest_slug) values ('f097e035-c64b-499d-a203-345d923f934d', 'coffee') on conflict do nothing;
insert into public.profile_interests (profile_id, interest_slug) values ('f097e035-c64b-499d-a203-345d923f934d', 'hiking') on conflict do nothing;
insert into public.profile_interests (profile_id, interest_slug) values ('f097e035-c64b-499d-a203-345d923f934d', 'music') on conflict do nothing;
insert into public.profile_interests (profile_id, interest_slug) values ('f097e035-c64b-499d-a203-345d923f934d', 'college') on conflict do nothing;
update public.profiles set bio = 'Climber, board game hoarder, disc golf enjoyer.', home_city = 'Columbus', display_name = 'Sam Kowalski', username = 'sam_k' where id = '1841f2ef-9435-49e0-ab03-f1e4c6744209';
insert into public.profile_interests (profile_id, interest_slug) values ('1841f2ef-9435-49e0-ab03-f1e4c6744209', 'climbing') on conflict do nothing;
insert into public.profile_interests (profile_id, interest_slug) values ('1841f2ef-9435-49e0-ab03-f1e4c6744209', 'board-games') on conflict do nothing;
insert into public.profile_interests (profile_id, interest_slug) values ('1841f2ef-9435-49e0-ab03-f1e4c6744209', 'outdoors') on conflict do nothing;
insert into public.profile_interests (profile_id, interest_slug) values ('1841f2ef-9435-49e0-ab03-f1e4c6744209', 'gaming') on conflict do nothing;
update public.profiles set bio = 'Organizes run club Thursdays. Ask me about routes.', home_city = 'Columbus', display_name = 'Priya Natarajan', username = 'priya' where id = '28572a41-206d-4bd8-a853-31ab1a437aea';
insert into public.profile_interests (profile_id, interest_slug) values ('28572a41-206d-4bd8-a853-31ab1a437aea', 'running') on conflict do nothing;
insert into public.profile_interests (profile_id, interest_slug) values ('28572a41-206d-4bd8-a853-31ab1a437aea', 'fitness') on conflict do nothing;
insert into public.profile_interests (profile_id, interest_slug) values ('28572a41-206d-4bd8-a853-31ab1a437aea', 'cycling') on conflict do nothing;
insert into public.profile_interests (profile_id, interest_slug) values ('28572a41-206d-4bd8-a853-31ab1a437aea', 'dogs') on conflict do nothing;
insert into public.profile_interests (profile_id, interest_slug) values ('28572a41-206d-4bd8-a853-31ab1a437aea', 'social') on conflict do nothing;
update public.profiles set bio = 'Printmaker. Community market regular. Knows every mural.', home_city = 'Columbus', display_name = 'Devin Hale', username = 'dev' where id = 'b2431795-ed35-49ac-a89b-74286bd6feeb';
insert into public.profile_interests (profile_id, interest_slug) values ('b2431795-ed35-49ac-a89b-74286bd6feeb', 'art') on conflict do nothing;
insert into public.profile_interests (profile_id, interest_slug) values ('b2431795-ed35-49ac-a89b-74286bd6feeb', 'volunteering') on conflict do nothing;
insert into public.profile_interests (profile_id, interest_slug) values ('b2431795-ed35-49ac-a89b-74286bd6feeb', 'social') on conflict do nothing;
insert into public.profile_interests (profile_id, interest_slug) values ('b2431795-ed35-49ac-a89b-74286bd6feeb', 'music') on conflict do nothing;
update public.profiles set bio = 'Here for the date spots that don''t cost $90 a head.', home_city = 'Columbus', display_name = 'Lena Fischer', username = 'lena' where id = 'ee4edfe3-9370-441b-a004-14b4bfff0b9d';
insert into public.profile_interests (profile_id, interest_slug) values ('ee4edfe3-9370-441b-a004-14b4bfff0b9d', 'date-night') on conflict do nothing;
insert into public.profile_interests (profile_id, interest_slug) values ('ee4edfe3-9370-441b-a004-14b4bfff0b9d', 'food') on conflict do nothing;
insert into public.profile_interests (profile_id, interest_slug) values ('ee4edfe3-9370-441b-a004-14b4bfff0b9d', 'nightlife') on conflict do nothing;
insert into public.profile_interests (profile_id, interest_slug) values ('ee4edfe3-9370-441b-a004-14b4bfff0b9d', 'art') on conflict do nothing;
update public.profiles set bio = 'Sand volleyball, pickleball, whatever''s got a net.', home_city = 'Columbus', display_name = 'Marcus Bell', username = 'marcus' where id = 'f6e4d056-f565-41b4-a2e0-f9347bbf87df';
insert into public.profile_interests (profile_id, interest_slug) values ('f6e4d056-f565-41b4-a2e0-f9347bbf87df', 'pickup-sports') on conflict do nothing;
insert into public.profile_interests (profile_id, interest_slug) values ('f6e4d056-f565-41b4-a2e0-f9347bbf87df', 'sports') on conflict do nothing;
insert into public.profile_interests (profile_id, interest_slug) values ('f6e4d056-f565-41b4-a2e0-f9347bbf87df', 'fitness') on conflict do nothing;
insert into public.profile_interests (profile_id, interest_slug) values ('f6e4d056-f565-41b4-a2e0-f9347bbf87df', 'social') on conflict do nothing;
update public.profiles set bio = 'Visiting from Cleveland most weekends. Tell me where to eat.', home_city = 'Cleveland', display_name = 'Nina Alvarez', username = 'nina' where id = 'b12fb965-a620-40e9-a0a8-8d379dcbbf40';
insert into public.profile_interests (profile_id, interest_slug) values ('b12fb965-a620-40e9-a0a8-8d379dcbbf40', 'food') on conflict do nothing;
insert into public.profile_interests (profile_id, interest_slug) values ('b12fb965-a620-40e9-a0a8-8d379dcbbf40', 'coffee') on conflict do nothing;
insert into public.profile_interests (profile_id, interest_slug) values ('b12fb965-a620-40e9-a0a8-8d379dcbbf40', 'art') on conflict do nothing;
insert into public.profile_interests (profile_id, interest_slug) values ('b12fb965-a620-40e9-a0a8-8d379dcbbf40', 'new-in-town') on conflict do nothing;

-- Places
insert into public.places (id, name, description, local_tip, category_slug, lat, lng, address, neighborhood, city, creator_id, visibility)
values ('a383ba25-872d-4154-ae60-51da7901394f', 'Cannon & Crown', 'Neighborhood bar with a wall of screens and a crowd that actually cares about the score. Not fancy, not loud outside of game time, and the kitchen stays open late on Saturdays.', 'Every Ohio State game plays with sound on the main screen. Get there 45 minutes before kickoff or you''re standing.', 'sports-bar', 39.9648, -82.9712, '1210 Oak St', 'Olde Towne East', 'Columbus', '3eb1d493-2346-45eb-ac2f-e4ea355f946a', 'public')
on conflict (id) do nothing;
insert into public.place_tags (place_id, interest_slug) values ('a383ba25-872d-4154-ae60-51da7901394f', 'sports') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('a383ba25-872d-4154-ae60-51da7901394f', 'ohio-state') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('a383ba25-872d-4154-ae60-51da7901394f', 'social') on conflict do nothing;
insert into public.places (id, name, description, local_tip, category_slug, lat, lng, address, neighborhood, city, creator_id, visibility)
values ('3e683576-5d71-4b74-a145-2a9d875afe56', 'Tuttle Lot Fields', 'Two full-size grass pitches behind the parking lot. Nets are usually up, lights until 10pm. This is where the regular Sunday pickup happens.', 'Sunday 10am pickup is all levels; bring a light and a dark shirt. Weekday evenings are quieter if you want touches.', 'pickup-sports', 40.0043, -83.0197, null, 'University District', 'Columbus', '28300d2a-8dcf-4599-a2da-9c4bbcd955da', 'public')
on conflict (id) do nothing;
insert into public.place_tags (place_id, interest_slug) values ('3e683576-5d71-4b74-a145-2a9d875afe56', 'pickup-sports') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('3e683576-5d71-4b74-a145-2a9d875afe56', 'sports') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('3e683576-5d71-4b74-a145-2a9d875afe56', 'new-in-town') on conflict do nothing;
insert into public.places (id, name, description, local_tip, category_slug, lat, lng, address, neighborhood, city, creator_id, visibility)
values ('9bfbeec3-4953-4f7b-a0bb-b5eae87a8136', 'Thurman Hollow Courts', 'Two outdoor full courts with decent rims and a resurfaced floor. Runs get competitive after 6pm on weekdays.', 'Winners stay. Show up by 5:45 to get in the first game; after 7 it''s a long wait.', 'pickup-sports', 40.0161, -83.0072, null, 'Old North', 'Columbus', 'f6e4d056-f565-41b4-a2e0-f9347bbf87df', 'public')
on conflict (id) do nothing;
insert into public.place_tags (place_id, interest_slug) values ('9bfbeec3-4953-4f7b-a0bb-b5eae87a8136', 'pickup-sports') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('9bfbeec3-4953-4f7b-a0bb-b5eae87a8136', 'sports') on conflict do nothing;
insert into public.places (id, name, description, local_tip, category_slug, lat, lng, address, neighborhood, city, creator_id, visibility)
values ('949fc154-9b49-4bc6-abe7-fdfa8e05a5f1', 'Ridgeline Loop', 'A 3.4-mile loop along the ravine with two real climbs and a river overlook halfway. Mostly dirt, some roots, very runnable.', 'Go counter-clockwise so the steep bit is a descent. Sunrise from the overlook is the reason people set alarms.', 'outdoors', 40.0325, -83.0231, null, 'Clintonville', 'Columbus', 'f097e035-c64b-499d-a203-345d923f934d', 'locals')
on conflict (id) do nothing;
insert into public.place_tags (place_id, interest_slug) values ('949fc154-9b49-4bc6-abe7-fdfa8e05a5f1', 'hiking') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('949fc154-9b49-4bc6-abe7-fdfa8e05a5f1', 'running') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('949fc154-9b49-4bc6-abe7-fdfa8e05a5f1', 'outdoors') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('949fc154-9b49-4bc6-abe7-fdfa8e05a5f1', 'dogs') on conflict do nothing;
insert into public.places (id, name, description, local_tip, category_slug, lat, lng, address, neighborhood, city, creator_id, visibility)
values ('2ec75da8-eeff-459c-acdb-da9200da2e10', 'Little Alley Dumpling', 'Six-seat counter down an alley off High Street. Hand-folded dumplings, one soup, cash preferred. Owner will remember your order.', 'Get the pan-fried pork and the cucumber salad. Twelve dumplings is under ten dollars.', 'food', 39.9803, -83.0059, 'Alley behind 900 N High St', 'Short North', 'Columbus', '28300d2a-8dcf-4599-a2da-9c4bbcd955da', 'public')
on conflict (id) do nothing;
insert into public.place_tags (place_id, interest_slug) values ('2ec75da8-eeff-459c-acdb-da9200da2e10', 'food') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('2ec75da8-eeff-459c-acdb-da9200da2e10', 'cheap-eats') on conflict do nothing;
insert into public.places (id, name, description, local_tip, category_slug, lat, lng, address, neighborhood, city, creator_id, visibility)
values ('e3cfa28d-3ac1-4c8c-ab2a-26a7115891b7', 'The Annex Reading Room', 'The back room of a bookshop that quietly turned into the best study space in the neighborhood. Long tables, outlets at every seat, nobody plays music.', 'Buy a coffee, then take the stairs to the mezzanine. Weeknights after 7 it empties out.', 'coffee-study', 39.9575, -83.0215, '330 W Broad St', 'Franklinton', 'Columbus', 'f097e035-c64b-499d-a203-345d923f934d', 'public')
on conflict (id) do nothing;
insert into public.place_tags (place_id, interest_slug) values ('e3cfa28d-3ac1-4c8c-ab2a-26a7115891b7', 'studying') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('e3cfa28d-3ac1-4c8c-ab2a-26a7115891b7', 'coffee') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('e3cfa28d-3ac1-4c8c-ab2a-26a7115891b7', 'college') on conflict do nothing;
insert into public.places (id, name, description, local_tip, category_slug, lat, lng, address, neighborhood, city, creator_id, visibility)
values ('2a29e970-8465-4211-ade2-d3c580e243ec', 'Boulder & Bramble', 'Bouldering-only gym in a converted warehouse. Friendly setting crew, resets a wall every week, has a real community night on Wednesdays.', 'Wednesday beginner night includes shoes and a 30-minute intro. Go as a stranger, leave with a crew.', 'fitness', 39.9812, -83.0412, '1550 W 3rd Ave', 'Grandview Heights', 'Columbus', '1841f2ef-9435-49e0-ab03-f1e4c6744209', 'public')
on conflict (id) do nothing;
insert into public.place_tags (place_id, interest_slug) values ('2a29e970-8465-4211-ade2-d3c580e243ec', 'climbing') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('2a29e970-8465-4211-ade2-d3c580e243ec', 'fitness') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('2a29e970-8465-4211-ade2-d3c580e243ec', 'social') on conflict do nothing;
insert into public.places (id, name, description, local_tip, category_slug, lat, lng, address, neighborhood, city, creator_id, visibility)
values ('52e68e92-83fd-4a4e-a560-4a05b9f3c0e4', 'Brickyard Sunset Steps', 'Wide public steps down to the river, facing west. Bring takeout and watch the skyline turn orange. Free, quiet, and somehow never crowded.', 'Grab dumplings from Little Alley on the way. Arrive 20 minutes before sunset for the good seats.', 'date-spot', 39.9596, -83.0108, null, 'Franklinton', 'Columbus', 'ee4edfe3-9370-441b-a004-14b4bfff0b9d', 'public')
on conflict (id) do nothing;
insert into public.place_tags (place_id, interest_slug) values ('52e68e92-83fd-4a4e-a560-4a05b9f3c0e4', 'date-night') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('52e68e92-83fd-4a4e-a560-4a05b9f3c0e4', 'cheap-eats') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('52e68e92-83fd-4a4e-a560-4a05b9f3c0e4', 'outdoors') on conflict do nothing;
insert into public.places (id, name, description, local_tip, category_slug, lat, lng, address, neighborhood, city, creator_id, visibility)
values ('beea2691-9686-47f7-aad9-a615d5a27745', 'Meeple Cellar', 'Basement board game cafe with a library of 600+ games and staff who will teach anything. Table fee is $5, waived if you order food.', 'Thursdays are open-table night: sit down at any table with an empty seat and you''re in.', 'gaming-hobby', 39.9452, -83.0008, '620 S Front St', 'Brewery District', 'Columbus', '1841f2ef-9435-49e0-ab03-f1e4c6744209', 'public')
on conflict (id) do nothing;
insert into public.place_tags (place_id, interest_slug) values ('beea2691-9686-47f7-aad9-a615d5a27745', 'board-games') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('beea2691-9686-47f7-aad9-a615d5a27745', 'gaming') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('beea2691-9686-47f7-aad9-a615d5a27745', 'social') on conflict do nothing;
insert into public.places (id, name, description, local_tip, category_slug, lat, lng, address, neighborhood, city, creator_id, visibility)
values ('5759b20e-3cf0-4fef-a0d0-65395e622c35', 'Fourth Street Basement', 'DIY venue under a print shop. Local bands, $10 at the door, all ages until 10. Shows are announced on a chalkboard out front and nowhere else.', 'Walk by on Tuesdays to read the chalkboard for the weekend lineup. Bring cash and earplugs.', 'music', 39.9787, -82.9972, '45 E 4th Ave', 'Italian Village', 'Columbus', 'b2431795-ed35-49ac-a89b-74286bd6feeb', 'locals')
on conflict (id) do nothing;
insert into public.place_tags (place_id, interest_slug) values ('5759b20e-3cf0-4fef-a0d0-65395e622c35', 'music') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('5759b20e-3cf0-4fef-a0d0-65395e622c35', 'nightlife') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('5759b20e-3cf0-4fef-a0d0-65395e622c35', 'art') on conflict do nothing;
insert into public.places (id, name, description, local_tip, category_slug, lat, lng, address, neighborhood, city, creator_id, visibility)
values ('4eab7b3a-cbc3-450b-a6c6-6dd69761f9b5', 'Hollow Oak Print Studio', 'Community screen-printing studio. Open studio hours on weekends, monthly print nights, and a wall of prints from people who learned here.', 'Open studio is $15 for the day including ink. Bring your own blank shirts or totes.', 'arts', 39.977, -82.9955, '51 E 4th Ave', 'Italian Village', 'Columbus', 'b2431795-ed35-49ac-a89b-74286bd6feeb', 'public')
on conflict (id) do nothing;
insert into public.place_tags (place_id, interest_slug) values ('4eab7b3a-cbc3-450b-a6c6-6dd69761f9b5', 'art') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('4eab7b3a-cbc3-450b-a6c6-6dd69761f9b5', 'social') on conflict do nothing;
insert into public.places (id, name, description, local_tip, category_slug, lat, lng, address, neighborhood, city, creator_id, visibility)
values ('aaac64e4-94fa-4520-ad18-bf10e1ec8dad', 'Grange Night Market', 'Second-Friday evening market in a church parking lot: food stalls, vintage, plants, and a local band. Very easy place to talk to strangers.', 'The dumpling stand sells out by 7:30. Bring a folding chair for the band.', 'community', 39.9662, -82.9378, '2200 E Main St', 'Bexley', 'Columbus', 'b2431795-ed35-49ac-a89b-74286bd6feeb', 'public')
on conflict (id) do nothing;
insert into public.place_tags (place_id, interest_slug) values ('aaac64e4-94fa-4520-ad18-bf10e1ec8dad', 'social') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('aaac64e4-94fa-4520-ad18-bf10e1ec8dad', 'food') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('aaac64e4-94fa-4520-ad18-bf10e1ec8dad', 'new-in-town') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('aaac64e4-94fa-4520-ad18-bf10e1ec8dad', 'music') on conflict do nothing;
insert into public.places (id, name, description, local_tip, category_slug, lat, lng, address, neighborhood, city, creator_id, visibility)
values ('6c836fab-455f-444a-ae2f-7e5705697e2f', 'Lantern Bowl', 'Six lanes of duckpin bowling in the back of a bar. Cheap games, good jukebox, no shoe rental needed.', 'Lanes are first-come. Put your name on the clipboard and grab a drink; the wait is usually one round.', 'nightlife', 39.9748, -83.0041, '780 N High St', 'Short North', 'Columbus', '3eb1d493-2346-45eb-ac2f-e4ea355f946a', 'public')
on conflict (id) do nothing;
insert into public.place_tags (place_id, interest_slug) values ('6c836fab-455f-444a-ae2f-7e5705697e2f', 'nightlife') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('6c836fab-455f-444a-ae2f-7e5705697e2f', 'social') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('6c836fab-455f-444a-ae2f-7e5705697e2f', 'date-night') on conflict do nothing;
insert into public.places (id, name, description, local_tip, category_slug, lat, lng, address, neighborhood, city, creator_id, visibility)
values ('562fc378-af83-4130-af42-843a0c5a1049', 'Copper Kettle Run Club Corner', 'The coffee shop corner where the Thursday run club meets. 5k and 8k routes, walkers welcome, coffee discount after.', 'Meet at 6:20pm for a 6:30 start. The 8k group turns left at the bridge; the 5k group goes right.', 'fitness', 40.0215, -83.0165, '3200 N High St', 'Clintonville', 'Columbus', '28572a41-206d-4bd8-a853-31ab1a437aea', 'public')
on conflict (id) do nothing;
insert into public.place_tags (place_id, interest_slug) values ('562fc378-af83-4130-af42-843a0c5a1049', 'running') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('562fc378-af83-4130-af42-843a0c5a1049', 'fitness') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('562fc378-af83-4130-af42-843a0c5a1049', 'social') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('562fc378-af83-4130-af42-843a0c5a1049', 'coffee') on conflict do nothing;
insert into public.places (id, name, description, local_tip, category_slug, lat, lng, address, neighborhood, city, creator_id, visibility)
values ('f4b42187-458d-4725-a416-4ef90ca25a42', 'Sawmill Disc Golf Meadow', 'Nine-hole disc golf course through a meadow and a stand of pines. Free, rarely busy on weekday mornings.', 'Hole 6 plays over the creek; bring a disc you don''t love. Loaner discs at the shed on weekends.', 'outdoors', 40.0111, -83.0552, null, 'Upper Arlington', 'Columbus', '1841f2ef-9435-49e0-ab03-f1e4c6744209', 'public')
on conflict (id) do nothing;
insert into public.place_tags (place_id, interest_slug) values ('f4b42187-458d-4725-a416-4ef90ca25a42', 'outdoors') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('f4b42187-458d-4725-a416-4ef90ca25a42', 'social') on conflict do nothing;
insert into public.places (id, name, description, local_tip, category_slug, lat, lng, address, neighborhood, city, creator_id, visibility)
values ('ca4864c5-2328-449c-a782-1a48653608cd', 'Brightwater Kayak Put-in', 'Gravel ramp with easy parking and a calm two-mile paddle downstream to the next take-out. Rentals nearby on weekends.', 'Paddle upstream first so the return is easy. Sunset paddles are the move in September.', 'outdoors', 39.9532, -83.0166, null, 'Franklinton', 'Columbus', '28572a41-206d-4bd8-a853-31ab1a437aea', 'public')
on conflict (id) do nothing;
insert into public.place_tags (place_id, interest_slug) values ('ca4864c5-2328-449c-a782-1a48653608cd', 'outdoors') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('ca4864c5-2328-449c-a782-1a48653608cd', 'date-night') on conflict do nothing;
insert into public.places (id, name, description, local_tip, category_slug, lat, lng, address, neighborhood, city, creator_id, visibility)
values ('05693bb3-4b18-4463-aa86-6f0866d70bd7', 'Buckeye Basement Tacos', 'Late-night taco window in the basement of a student building. Three tacos and a drink for $8, open until 2am on weekends.', 'The al pastor runs out by 1am. The line moves fast; the salsa verde does not mess around.', 'food', 39.9968, -83.0075, '1800 N High St', 'University District', 'Columbus', '28300d2a-8dcf-4599-a2da-9c4bbcd955da', 'public')
on conflict (id) do nothing;
insert into public.place_tags (place_id, interest_slug) values ('05693bb3-4b18-4463-aa86-6f0866d70bd7', 'food') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('05693bb3-4b18-4463-aa86-6f0866d70bd7', 'cheap-eats') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('05693bb3-4b18-4463-aa86-6f0866d70bd7', 'college') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('05693bb3-4b18-4463-aa86-6f0866d70bd7', 'nightlife') on conflict do nothing;
insert into public.places (id, name, description, local_tip, category_slug, lat, lng, address, neighborhood, city, creator_id, visibility)
values ('710b7e58-663b-4419-aea4-dac91a086872', 'Nightowl Study Lounge', '24-hour lounge with booths, whiteboards and a vending wall. Free with a student ID, $3 a day otherwise.', 'The corner booths have the only good outlets. After midnight it''s dead quiet.', 'coffee-study', 39.9992, -83.0121, '1990 N High St', 'University District', 'Columbus', 'f097e035-c64b-499d-a203-345d923f934d', 'public')
on conflict (id) do nothing;
insert into public.place_tags (place_id, interest_slug) values ('710b7e58-663b-4419-aea4-dac91a086872', 'studying') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('710b7e58-663b-4419-aea4-dac91a086872', 'college') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('710b7e58-663b-4419-aea4-dac91a086872', 'coffee') on conflict do nothing;
insert into public.places (id, name, description, local_tip, category_slug, lat, lng, address, neighborhood, city, creator_id, visibility)
values ('b1ce24bb-4b5d-463e-a460-f237bf6d472a', 'Riverbend Volleyball Pits', 'Four sand courts by the river with lights until 11. Open play most evenings; leagues take the far two courts on Tuesdays.', 'Courts 1 and 2 are always open play. Bring your own ball and a towel; the sand gets everywhere.', 'pickup-sports', 39.9868, -83.0381, null, 'Grandview Heights', 'Columbus', 'f6e4d056-f565-41b4-a2e0-f9347bbf87df', 'public')
on conflict (id) do nothing;
insert into public.place_tags (place_id, interest_slug) values ('b1ce24bb-4b5d-463e-a460-f237bf6d472a', 'pickup-sports') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('b1ce24bb-4b5d-463e-a460-f237bf6d472a', 'sports') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('b1ce24bb-4b5d-463e-a460-f237bf6d472a', 'social') on conflict do nothing;
insert into public.places (id, name, description, local_tip, category_slug, lat, lng, address, neighborhood, city, creator_id, visibility)
values ('e7fd6465-1870-4bdb-ae5e-f46f72cb2d06', 'Merion Rec Pickleball', 'Six courts at a small rec center. Open play mornings, ladder nights on Mondays, loaner paddles at the desk.', 'Open play 8-11am is beginner friendly. Monday ladder night is where the good players are.', 'pickup-sports', 39.9401, -82.9931, '1100 Parsons Ave', 'Merion Village', 'Columbus', 'f6e4d056-f565-41b4-a2e0-f9347bbf87df', 'public')
on conflict (id) do nothing;
insert into public.place_tags (place_id, interest_slug) values ('e7fd6465-1870-4bdb-ae5e-f46f72cb2d06', 'pickup-sports') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('e7fd6465-1870-4bdb-ae5e-f46f72cb2d06', 'sports') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('e7fd6465-1870-4bdb-ae5e-f46f72cb2d06', 'fitness') on conflict do nothing;
insert into public.places (id, name, description, local_tip, category_slug, lat, lng, address, neighborhood, city, creator_id, visibility)
values ('448ac9a2-5c47-4d61-addd-169244cb30a2', 'Cobblestone Chess Corner', 'Four stone chess tables under a big sycamore. Regulars most afternoons, casual games, blitz on Saturdays.', 'Bring a clock and someone will play you. Saturday blitz starts around 2.', 'gaming-hobby', 39.9735, -83.0027, null, 'Victorian Village', 'Columbus', '1841f2ef-9435-49e0-ab03-f1e4c6744209', 'public')
on conflict (id) do nothing;
insert into public.place_tags (place_id, interest_slug) values ('448ac9a2-5c47-4d61-addd-169244cb30a2', 'board-games') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('448ac9a2-5c47-4d61-addd-169244cb30a2', 'social') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('448ac9a2-5c47-4d61-addd-169244cb30a2', 'gaming') on conflict do nothing;
insert into public.places (id, name, description, local_tip, category_slug, lat, lng, address, neighborhood, city, creator_id, visibility)
values ('49ebfa09-a751-4e9f-adbb-62441be568ce', 'Wren Street Wine Porch', 'Tiny wine bar with a wraparound porch and $8 glasses. String lights, a record player, and a two-hour table limit nobody enforces.', 'The porch is first-come; Tuesdays and Wednesdays you can always get a spot. Cheese board is big enough for two.', 'date-spot', 39.9483, -82.9902, '215 Thurman Ave', 'German Village', 'Columbus', 'ee4edfe3-9370-441b-a004-14b4bfff0b9d', 'public')
on conflict (id) do nothing;
insert into public.place_tags (place_id, interest_slug) values ('49ebfa09-a751-4e9f-adbb-62441be568ce', 'date-night') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('49ebfa09-a751-4e9f-adbb-62441be568ce', 'nightlife') on conflict do nothing;
insert into public.places (id, name, description, local_tip, category_slug, lat, lng, address, neighborhood, city, creator_id, visibility)
values ('243e3950-03d9-4e54-a82f-69906ae98ff2', 'The Lumen Rooftop', 'Hotel rooftop that lets non-guests up. No cover, decent view of the skyline, cocktails are fine and the sunset is not.', 'Go on a weeknight at 8; weekends have a line. Take the elevator to 12 then the stairs.', 'nightlife', 39.9622, -82.9993, '70 E Gay St', 'Downtown', 'Columbus', 'ee4edfe3-9370-441b-a004-14b4bfff0b9d', 'public')
on conflict (id) do nothing;
insert into public.place_tags (place_id, interest_slug) values ('243e3950-03d9-4e54-a82f-69906ae98ff2', 'nightlife') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('243e3950-03d9-4e54-a82f-69906ae98ff2', 'date-night') on conflict do nothing;
insert into public.places (id, name, description, local_tip, category_slug, lat, lng, address, neighborhood, city, creator_id, visibility)
values ('7000030a-8bcf-4a9e-a24a-b771f4bd4a35', 'Northend Thrift Alley', 'Three thrift shops in a row on one block, plus a record store. Good for furnishing a first apartment on a budget.', 'The middle shop restocks Wednesday mornings. Furniture goes fast.', 'other', 40.0256, -83.0148, '3400 N High St', 'Clintonville', 'Columbus', '28300d2a-8dcf-4599-a2da-9c4bbcd955da', 'public')
on conflict (id) do nothing;
insert into public.place_tags (place_id, interest_slug) values ('7000030a-8bcf-4a9e-a24a-b771f4bd4a35', 'new-in-town') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('7000030a-8bcf-4a9e-a24a-b771f4bd4a35', 'cheap-eats') on conflict do nothing;
insert into public.places (id, name, description, local_tip, category_slug, lat, lng, address, neighborhood, city, creator_id, visibility)
values ('2c7ed982-6d16-4005-ad3d-c6cf72ba901e', 'Overpass Skate Bowl', 'Concrete bowl and a small street section under the highway. Covered, so it works in the rain. Friendly to beginners before noon.', 'Mornings are quiet and forgiving. Bring water; there''s no fountain.', 'outdoors', 39.9553, -83.0055, null, 'Franklinton', 'Columbus', 'b2431795-ed35-49ac-a89b-74286bd6feeb', 'public')
on conflict (id) do nothing;
insert into public.place_tags (place_id, interest_slug) values ('2c7ed982-6d16-4005-ad3d-c6cf72ba901e', 'outdoors') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('2c7ed982-6d16-4005-ad3d-c6cf72ba901e', 'fitness') on conflict do nothing;
insert into public.places (id, name, description, local_tip, category_slug, lat, lng, address, neighborhood, city, creator_id, visibility)
values ('c91aeba1-5c55-41a5-acfb-5c45d52dcab8', 'Hilltop Kickabout', 'Small-sided pitch behind a community center. Wednesday evening 7v7 is a fixture; very mixed levels, very friendly.', 'Wednesday 6:30pm. Someone always brings pinnies. Say hi to whoever has the ball bag.', 'pickup-sports', 39.9622, -83.0648, '2600 W Broad St', 'Hilltop', 'Columbus', '3eb1d493-2346-45eb-ac2f-e4ea355f946a', 'public')
on conflict (id) do nothing;
insert into public.place_tags (place_id, interest_slug) values ('c91aeba1-5c55-41a5-acfb-5c45d52dcab8', 'pickup-sports') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('c91aeba1-5c55-41a5-acfb-5c45d52dcab8', 'sports') on conflict do nothing;
insert into public.place_tags (place_id, interest_slug) values ('c91aeba1-5c55-41a5-acfb-5c45d52dcab8', 'new-in-town') on conflict do nothing;

-- Ratings (aggregates are recomputed by trigger)
insert into public.place_ratings (place_id, user_id, score, note) values ('a383ba25-872d-4154-ae60-51da7901394f', '3eb1d493-2346-45eb-ac2f-e4ea355f946a', 5, 'The only bar that turns the sound on.') on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('a383ba25-872d-4154-ae60-51da7901394f', '28300d2a-8dcf-4599-a2da-9c4bbcd955da', 4, null) on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('a383ba25-872d-4154-ae60-51da7901394f', 'f6e4d056-f565-41b4-a2e0-f9347bbf87df', 5, 'Wings are underrated.') on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('3e683576-5d71-4b74-a145-2a9d875afe56', '28300d2a-8dcf-4599-a2da-9c4bbcd955da', 5, 'Made friends here in my first week.') on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('3e683576-5d71-4b74-a145-2a9d875afe56', 'f6e4d056-f565-41b4-a2e0-f9347bbf87df', 4, null) on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('3e683576-5d71-4b74-a145-2a9d875afe56', '3eb1d493-2346-45eb-ac2f-e4ea355f946a', 4, null) on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('9bfbeec3-4953-4f7b-a0bb-b5eae87a8136', 'f6e4d056-f565-41b4-a2e0-f9347bbf87df', 4, 'Good runs, long waits.') on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('9bfbeec3-4953-4f7b-a0bb-b5eae87a8136', '3eb1d493-2346-45eb-ac2f-e4ea355f946a', 4, null) on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('949fc154-9b49-4bc6-abe7-fdfa8e05a5f1', 'f097e035-c64b-499d-a203-345d923f934d', 5, 'The overlook at sunrise is unreal.') on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('949fc154-9b49-4bc6-abe7-fdfa8e05a5f1', '28572a41-206d-4bd8-a853-31ab1a437aea', 5, 'Best trail run in the city.') on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('949fc154-9b49-4bc6-abe7-fdfa8e05a5f1', '1841f2ef-9435-49e0-ab03-f1e4c6744209', 4, null) on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('2ec75da8-eeff-459c-acdb-da9200da2e10', '28300d2a-8dcf-4599-a2da-9c4bbcd955da', 5, 'Cheapest great meal I''ve found.') on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('2ec75da8-eeff-459c-acdb-da9200da2e10', 'ee4edfe3-9370-441b-a004-14b4bfff0b9d', 5, null) on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('2ec75da8-eeff-459c-acdb-da9200da2e10', 'f097e035-c64b-499d-a203-345d923f934d', 4, null) on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('e3cfa28d-3ac1-4c8c-ab2a-26a7115891b7', 'f097e035-c64b-499d-a203-345d923f934d', 5, 'Wrote my whole thesis here.') on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('e3cfa28d-3ac1-4c8c-ab2a-26a7115891b7', '28300d2a-8dcf-4599-a2da-9c4bbcd955da', 4, null) on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('2a29e970-8465-4211-ade2-d3c580e243ec', '1841f2ef-9435-49e0-ab03-f1e4c6744209', 5, null) on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('2a29e970-8465-4211-ade2-d3c580e243ec', 'ee4edfe3-9370-441b-a004-14b4bfff0b9d', 4, 'Beginner night was so welcoming.') on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('52e68e92-83fd-4a4e-a560-4a05b9f3c0e4', 'ee4edfe3-9370-441b-a004-14b4bfff0b9d', 5, 'Free date night, every time.') on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('52e68e92-83fd-4a4e-a560-4a05b9f3c0e4', '28572a41-206d-4bd8-a853-31ab1a437aea', 4, null) on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('beea2691-9686-47f7-aad9-a615d5a27745', '1841f2ef-9435-49e0-ab03-f1e4c6744209', 5, null) on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('beea2691-9686-47f7-aad9-a615d5a27745', 'b2431795-ed35-49ac-a89b-74286bd6feeb', 4, null) on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('beea2691-9686-47f7-aad9-a615d5a27745', '3eb1d493-2346-45eb-ac2f-e4ea355f946a', 4, null) on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('5759b20e-3cf0-4fef-a0d0-65395e622c35', 'b2431795-ed35-49ac-a89b-74286bd6feeb', 5, null) on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('5759b20e-3cf0-4fef-a0d0-65395e622c35', 'f097e035-c64b-499d-a203-345d923f934d', 4, 'Loud in the best way.') on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('4eab7b3a-cbc3-450b-a6c6-6dd69761f9b5', 'b2431795-ed35-49ac-a89b-74286bd6feeb', 5, null) on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('aaac64e4-94fa-4520-ad18-bf10e1ec8dad', 'b2431795-ed35-49ac-a89b-74286bd6feeb', 4, null) on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('aaac64e4-94fa-4520-ad18-bf10e1ec8dad', '28300d2a-8dcf-4599-a2da-9c4bbcd955da', 5, 'Talked to more people here than in a month.') on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('6c836fab-455f-444a-ae2f-7e5705697e2f', '3eb1d493-2346-45eb-ac2f-e4ea355f946a', 4, null) on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('6c836fab-455f-444a-ae2f-7e5705697e2f', 'ee4edfe3-9370-441b-a004-14b4bfff0b9d', 4, null) on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('562fc378-af83-4130-af42-843a0c5a1049', '28572a41-206d-4bd8-a853-31ab1a437aea', 5, null) on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('562fc378-af83-4130-af42-843a0c5a1049', '28300d2a-8dcf-4599-a2da-9c4bbcd955da', 5, null) on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('f4b42187-458d-4725-a416-4ef90ca25a42', '1841f2ef-9435-49e0-ab03-f1e4c6744209', 4, null) on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('ca4864c5-2328-449c-a782-1a48653608cd', '28572a41-206d-4bd8-a853-31ab1a437aea', 4, null) on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('05693bb3-4b18-4463-aa86-6f0866d70bd7', '28300d2a-8dcf-4599-a2da-9c4bbcd955da', 4, null) on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('05693bb3-4b18-4463-aa86-6f0866d70bd7', 'f097e035-c64b-499d-a203-345d923f934d', 5, '2am lifesaver.') on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('710b7e58-663b-4419-aea4-dac91a086872', 'f097e035-c64b-499d-a203-345d923f934d', 4, null) on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('b1ce24bb-4b5d-463e-a460-f237bf6d472a', 'f6e4d056-f565-41b4-a2e0-f9347bbf87df', 5, null) on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('b1ce24bb-4b5d-463e-a460-f237bf6d472a', '28572a41-206d-4bd8-a853-31ab1a437aea', 4, null) on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('e7fd6465-1870-4bdb-ae5e-f46f72cb2d06', 'f6e4d056-f565-41b4-a2e0-f9347bbf87df', 4, null) on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('448ac9a2-5c47-4d61-addd-169244cb30a2', '1841f2ef-9435-49e0-ab03-f1e4c6744209', 4, null) on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('49ebfa09-a751-4e9f-adbb-62441be568ce', 'ee4edfe3-9370-441b-a004-14b4bfff0b9d', 5, 'Porch + record player = yes.') on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('49ebfa09-a751-4e9f-adbb-62441be568ce', '3eb1d493-2346-45eb-ac2f-e4ea355f946a', 4, null) on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('243e3950-03d9-4e54-a82f-69906ae98ff2', 'ee4edfe3-9370-441b-a004-14b4bfff0b9d', 3, 'View good, drinks fine.') on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('7000030a-8bcf-4a9e-a24a-b771f4bd4a35', '28300d2a-8dcf-4599-a2da-9c4bbcd955da', 4, null) on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('2c7ed982-6d16-4005-ad3d-c6cf72ba901e', 'b2431795-ed35-49ac-a89b-74286bd6feeb', 4, null) on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('c91aeba1-5c55-41a5-acfb-5c45d52dcab8', '3eb1d493-2346-45eb-ac2f-e4ea355f946a', 4, null) on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;
insert into public.place_ratings (place_id, user_id, score, note) values ('c91aeba1-5c55-41a5-acfb-5c45d52dcab8', '28300d2a-8dcf-4599-a2da-9c4bbcd955da', 5, null) on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;

-- Saved places
insert into public.saved_places (user_id, place_id) values ('28300d2a-8dcf-4599-a2da-9c4bbcd955da', 'a383ba25-872d-4154-ae60-51da7901394f') on conflict do nothing;
insert into public.saved_places (user_id, place_id) values ('28300d2a-8dcf-4599-a2da-9c4bbcd955da', '949fc154-9b49-4bc6-abe7-fdfa8e05a5f1') on conflict do nothing;
insert into public.saved_places (user_id, place_id) values ('28300d2a-8dcf-4599-a2da-9c4bbcd955da', 'beea2691-9686-47f7-aad9-a615d5a27745') on conflict do nothing;
insert into public.saved_places (user_id, place_id) values ('28300d2a-8dcf-4599-a2da-9c4bbcd955da', '2a29e970-8465-4211-ade2-d3c580e243ec') on conflict do nothing;
insert into public.saved_places (user_id, place_id) values ('3eb1d493-2346-45eb-ac2f-e4ea355f946a', '2ec75da8-eeff-459c-acdb-da9200da2e10') on conflict do nothing;
insert into public.saved_places (user_id, place_id) values ('3eb1d493-2346-45eb-ac2f-e4ea355f946a', 'beea2691-9686-47f7-aad9-a615d5a27745') on conflict do nothing;
insert into public.saved_places (user_id, place_id) values ('f097e035-c64b-499d-a203-345d923f934d', '949fc154-9b49-4bc6-abe7-fdfa8e05a5f1') on conflict do nothing;
insert into public.saved_places (user_id, place_id) values ('f097e035-c64b-499d-a203-345d923f934d', '2ec75da8-eeff-459c-acdb-da9200da2e10') on conflict do nothing;
insert into public.saved_places (user_id, place_id) values ('f097e035-c64b-499d-a203-345d923f934d', '5759b20e-3cf0-4fef-a0d0-65395e622c35') on conflict do nothing;
insert into public.saved_places (user_id, place_id) values ('1841f2ef-9435-49e0-ab03-f1e4c6744209', '949fc154-9b49-4bc6-abe7-fdfa8e05a5f1') on conflict do nothing;
insert into public.saved_places (user_id, place_id) values ('1841f2ef-9435-49e0-ab03-f1e4c6744209', '448ac9a2-5c47-4d61-addd-169244cb30a2') on conflict do nothing;
insert into public.saved_places (user_id, place_id) values ('28572a41-206d-4bd8-a853-31ab1a437aea', 'ca4864c5-2328-449c-a782-1a48653608cd') on conflict do nothing;
insert into public.saved_places (user_id, place_id) values ('28572a41-206d-4bd8-a853-31ab1a437aea', '949fc154-9b49-4bc6-abe7-fdfa8e05a5f1') on conflict do nothing;
insert into public.saved_places (user_id, place_id) values ('b2431795-ed35-49ac-a89b-74286bd6feeb', 'aaac64e4-94fa-4520-ad18-bf10e1ec8dad') on conflict do nothing;
insert into public.saved_places (user_id, place_id) values ('ee4edfe3-9370-441b-a004-14b4bfff0b9d', '52e68e92-83fd-4a4e-a560-4a05b9f3c0e4') on conflict do nothing;
insert into public.saved_places (user_id, place_id) values ('ee4edfe3-9370-441b-a004-14b4bfff0b9d', '2ec75da8-eeff-459c-acdb-da9200da2e10') on conflict do nothing;
insert into public.saved_places (user_id, place_id) values ('f6e4d056-f565-41b4-a2e0-f9347bbf87df', '3e683576-5d71-4b74-a145-2a9d875afe56') on conflict do nothing;
insert into public.saved_places (user_id, place_id) values ('f6e4d056-f565-41b4-a2e0-f9347bbf87df', '9bfbeec3-4953-4f7b-a0bb-b5eae87a8136') on conflict do nothing;

-- Events (times are relative to seed time so the demo always has upcoming events)
insert into public.events (id, title, description, place_id, location_name, address, lat, lng, starts_at, ends_at, creator_id, category_slug, capacity)
values ('2194b5a2-2f6c-466a-af4d-cf70d0d11552', 'Sunday pickup soccer', 'Weekly all-levels pickup. We play 11v11 if numbers allow, otherwise split into two small-sided games. Bring a light and a dark shirt, water, and turf or cleats.', '3e683576-5d71-4b74-a145-2a9d875afe56', 'Tuttle Lot Fields', null, 40.0043, -83.0197, (date_trunc('day', now()) + interval '2 days' + interval '10 hours' + interval '0 minutes'), ((date_trunc('day', now()) + interval '2 days' + interval '10 hours' + interval '0 minutes') + interval '120 minutes'), '28300d2a-8dcf-4599-a2da-9c4bbcd955da', 'pickup-sports', 24)
on conflict (id) do nothing;
insert into public.event_tags (event_id, interest_slug) values ('2194b5a2-2f6c-466a-af4d-cf70d0d11552', 'pickup-sports') on conflict do nothing;
insert into public.event_tags (event_id, interest_slug) values ('2194b5a2-2f6c-466a-af4d-cf70d0d11552', 'sports') on conflict do nothing;
insert into public.event_tags (event_id, interest_slug) values ('2194b5a2-2f6c-466a-af4d-cf70d0d11552', 'new-in-town') on conflict do nothing;
insert into public.events (id, title, description, place_id, location_name, address, lat, lng, starts_at, ends_at, creator_id, category_slug, capacity)
values ('78a3b49a-b65b-46e5-aa7a-867722a97ea7', 'OSU game watch party', 'Big screen, sound on, tables reserved in the back for the FindMaxxing crew. Wear scarlet. Kitchen open the whole game.', 'a383ba25-872d-4154-ae60-51da7901394f', 'Cannon & Crown', '1210 Oak St', 39.9648, -82.9712, (date_trunc('day', now()) + interval '5 days' + interval '15 hours' + interval '30 minutes'), ((date_trunc('day', now()) + interval '5 days' + interval '15 hours' + interval '30 minutes') + interval '240 minutes'), '3eb1d493-2346-45eb-ac2f-e4ea355f946a', 'watch-party', 30)
on conflict (id) do nothing;
insert into public.event_tags (event_id, interest_slug) values ('78a3b49a-b65b-46e5-aa7a-867722a97ea7', 'sports') on conflict do nothing;
insert into public.event_tags (event_id, interest_slug) values ('78a3b49a-b65b-46e5-aa7a-867722a97ea7', 'ohio-state') on conflict do nothing;
insert into public.event_tags (event_id, interest_slug) values ('78a3b49a-b65b-46e5-aa7a-867722a97ea7', 'social') on conflict do nothing;
insert into public.events (id, title, description, place_id, location_name, address, lat, lng, starts_at, ends_at, creator_id, category_slug, capacity)
values ('93a5055c-5fb4-4d59-a82e-ac9bec6adced', 'Ridgeline sunrise hike', 'Counter-clockwise loop, easy pace, coffee at the overlook. Headlamp for the first 20 minutes. Dogs on leash welcome.', '949fc154-9b49-4bc6-abe7-fdfa8e05a5f1', 'Ridgeline Loop trailhead', null, 40.0325, -83.0231, (date_trunc('day', now()) + interval '3 days' + interval '6 hours' + interval '45 minutes'), ((date_trunc('day', now()) + interval '3 days' + interval '6 hours' + interval '45 minutes') + interval '90 minutes'), 'f097e035-c64b-499d-a203-345d923f934d', 'outdoors', null)
on conflict (id) do nothing;
insert into public.event_tags (event_id, interest_slug) values ('93a5055c-5fb4-4d59-a82e-ac9bec6adced', 'hiking') on conflict do nothing;
insert into public.event_tags (event_id, interest_slug) values ('93a5055c-5fb4-4d59-a82e-ac9bec6adced', 'outdoors') on conflict do nothing;
insert into public.event_tags (event_id, interest_slug) values ('93a5055c-5fb4-4d59-a82e-ac9bec6adced', 'dogs') on conflict do nothing;
insert into public.events (id, title, description, place_id, location_name, address, lat, lng, starts_at, ends_at, creator_id, category_slug, capacity)
values ('fb21e651-2c8f-40e8-a235-208e45de5816', 'Midterms study block', 'Silent focus blocks (50 on / 10 off) on the mezzanine. Any subject. Bring headphones; we''ll grab the long table.', 'e3cfa28d-3ac1-4c8c-ab2a-26a7115891b7', 'The Annex Reading Room', '330 W Broad St', 39.9575, -83.0215, (date_trunc('day', now()) + interval '1 days' + interval '18 hours' + interval '0 minutes'), ((date_trunc('day', now()) + interval '1 days' + interval '18 hours' + interval '0 minutes') + interval '180 minutes'), 'f097e035-c64b-499d-a203-345d923f934d', 'coffee-study', 12)
on conflict (id) do nothing;
insert into public.event_tags (event_id, interest_slug) values ('fb21e651-2c8f-40e8-a235-208e45de5816', 'studying') on conflict do nothing;
insert into public.event_tags (event_id, interest_slug) values ('fb21e651-2c8f-40e8-a235-208e45de5816', 'college') on conflict do nothing;
insert into public.events (id, title, description, place_id, location_name, address, lat, lng, starts_at, ends_at, creator_id, category_slug, capacity)
values ('0cb78784-f724-4d53-a12b-ff5eeec77fd7', 'Beginner climbing night', 'Never climbed? Perfect. Intro to bouldering, shoes included, then we climb together. Meet by the front desk.', '2a29e970-8465-4211-ade2-d3c580e243ec', 'Boulder & Bramble', '1550 W 3rd Ave', 39.9812, -83.0412, (date_trunc('day', now()) + interval '4 days' + interval '19 hours' + interval '0 minutes'), ((date_trunc('day', now()) + interval '4 days' + interval '19 hours' + interval '0 minutes') + interval '120 minutes'), '1841f2ef-9435-49e0-ab03-f1e4c6744209', 'fitness', 12)
on conflict (id) do nothing;
insert into public.event_tags (event_id, interest_slug) values ('0cb78784-f724-4d53-a12b-ff5eeec77fd7', 'climbing') on conflict do nothing;
insert into public.event_tags (event_id, interest_slug) values ('0cb78784-f724-4d53-a12b-ff5eeec77fd7', 'fitness') on conflict do nothing;
insert into public.event_tags (event_id, interest_slug) values ('0cb78784-f724-4d53-a12b-ff5eeec77fd7', 'social') on conflict do nothing;
insert into public.event_tags (event_id, interest_slug) values ('0cb78784-f724-4d53-a12b-ff5eeec77fd7', 'new-in-town') on conflict do nothing;
insert into public.events (id, title, description, place_id, location_name, address, lat, lng, starts_at, ends_at, creator_id, category_slug, capacity)
values ('9df47047-8be5-44da-aa22-3fc0e3fa7980', 'Open-table board game night', 'Sit anywhere with an empty seat. We''ll have Catan, Wingspan, Codenames and whatever the staff wants to teach.', 'beea2691-9686-47f7-aad9-a615d5a27745', 'Meeple Cellar', '620 S Front St', 39.9452, -83.0008, (date_trunc('day', now()) + interval '2 days' + interval '19 hours' + interval '0 minutes'), ((date_trunc('day', now()) + interval '2 days' + interval '19 hours' + interval '0 minutes') + interval '180 minutes'), '1841f2ef-9435-49e0-ab03-f1e4c6744209', 'gaming-hobby', 16)
on conflict (id) do nothing;
insert into public.event_tags (event_id, interest_slug) values ('9df47047-8be5-44da-aa22-3fc0e3fa7980', 'board-games') on conflict do nothing;
insert into public.event_tags (event_id, interest_slug) values ('9df47047-8be5-44da-aa22-3fc0e3fa7980', 'gaming') on conflict do nothing;
insert into public.event_tags (event_id, interest_slug) values ('9df47047-8be5-44da-aa22-3fc0e3fa7980', 'social') on conflict do nothing;
insert into public.events (id, title, description, place_id, location_name, address, lat, lng, starts_at, ends_at, creator_id, category_slug, capacity)
values ('7a909fa4-dd98-4bfe-a0b8-270abd366a08', 'Newcomers coffee walk', 'Slow walk through the Short North with coffee stops. Made for people who moved here in the last year. Zero agenda, just faces.', null, 'Short North arch at Goodale', 'N High St & Goodale St', 39.9738, -83.0043, (date_trunc('day', now()) + interval '6 days' + interval '10 hours' + interval '0 minutes'), ((date_trunc('day', now()) + interval '6 days' + interval '10 hours' + interval '0 minutes') + interval '90 minutes'), '28572a41-206d-4bd8-a853-31ab1a437aea', 'community', null)
on conflict (id) do nothing;
insert into public.event_tags (event_id, interest_slug) values ('7a909fa4-dd98-4bfe-a0b8-270abd366a08', 'new-in-town') on conflict do nothing;
insert into public.event_tags (event_id, interest_slug) values ('7a909fa4-dd98-4bfe-a0b8-270abd366a08', 'social') on conflict do nothing;
insert into public.event_tags (event_id, interest_slug) values ('7a909fa4-dd98-4bfe-a0b8-270abd366a08', 'coffee') on conflict do nothing;
insert into public.events (id, title, description, place_id, location_name, address, lat, lng, starts_at, ends_at, creator_id, category_slug, capacity)
values ('0b729311-7709-4f3a-ab0a-d9514f26be75', 'Basement show: three local bands', '$10 at the door, all ages until 10pm. Lineup on the chalkboard. Earplugs at the merch table.', '5759b20e-3cf0-4fef-a0d0-65395e622c35', 'Fourth Street Basement', '45 E 4th Ave', 39.9787, -82.9972, (date_trunc('day', now()) + interval '7 days' + interval '21 hours' + interval '0 minutes'), ((date_trunc('day', now()) + interval '7 days' + interval '21 hours' + interval '0 minutes') + interval '180 minutes'), 'b2431795-ed35-49ac-a89b-74286bd6feeb', 'music', 80)
on conflict (id) do nothing;
insert into public.event_tags (event_id, interest_slug) values ('0b729311-7709-4f3a-ab0a-d9514f26be75', 'music') on conflict do nothing;
insert into public.event_tags (event_id, interest_slug) values ('0b729311-7709-4f3a-ab0a-d9514f26be75', 'nightlife') on conflict do nothing;
insert into public.events (id, title, description, place_id, location_name, address, lat, lng, starts_at, ends_at, creator_id, category_slug, capacity)
values ('3d0704a2-f478-4819-a88a-20304708d229', '3v3 basketball run', 'Half-court 3s, games to 15, winners stay. Bring a ball if you have one.', '9bfbeec3-4953-4f7b-a0bb-b5eae87a8136', 'Thurman Hollow Courts', null, 40.0161, -83.0072, (date_trunc('day', now()) + interval '1 days' + interval '18 hours' + interval '0 minutes'), ((date_trunc('day', now()) + interval '1 days' + interval '18 hours' + interval '0 minutes') + interval '120 minutes'), 'f6e4d056-f565-41b4-a2e0-f9347bbf87df', 'pickup-sports', 12)
on conflict (id) do nothing;
insert into public.event_tags (event_id, interest_slug) values ('3d0704a2-f478-4819-a88a-20304708d229', 'pickup-sports') on conflict do nothing;
insert into public.event_tags (event_id, interest_slug) values ('3d0704a2-f478-4819-a88a-20304708d229', 'sports') on conflict do nothing;
insert into public.events (id, title, description, place_id, location_name, address, lat, lng, starts_at, ends_at, creator_id, category_slug, capacity)
values ('00bc1dba-cae4-48c9-a594-7ae7738cb2f4', 'Thursday run club', '5k and 8k routes from the corner. All paces, nobody gets dropped. Coffee discount after with the club sticker.', '562fc378-af83-4130-af42-843a0c5a1049', 'Copper Kettle Run Club Corner', '3200 N High St', 40.0215, -83.0165, (date_trunc('day', now()) + interval '3 days' + interval '18 hours' + interval '30 minutes'), ((date_trunc('day', now()) + interval '3 days' + interval '18 hours' + interval '30 minutes') + interval '75 minutes'), '28572a41-206d-4bd8-a853-31ab1a437aea', 'fitness', null)
on conflict (id) do nothing;
insert into public.event_tags (event_id, interest_slug) values ('00bc1dba-cae4-48c9-a594-7ae7738cb2f4', 'running') on conflict do nothing;
insert into public.event_tags (event_id, interest_slug) values ('00bc1dba-cae4-48c9-a594-7ae7738cb2f4', 'fitness') on conflict do nothing;
insert into public.event_tags (event_id, interest_slug) values ('00bc1dba-cae4-48c9-a594-7ae7738cb2f4', 'social') on conflict do nothing;
insert into public.events (id, title, description, place_id, location_name, address, lat, lng, starts_at, ends_at, creator_id, category_slug, capacity)
values ('5c641021-17b2-4952-af80-e084f0fc4a61', 'Print night: screen-print a tote', 'Learn to pull a screen and leave with a tote. Materials included. Beginners very welcome.', '4eab7b3a-cbc3-450b-a6c6-6dd69761f9b5', 'Hollow Oak Print Studio', '51 E 4th Ave', 39.977, -82.9955, (date_trunc('day', now()) + interval '9 days' + interval '18 hours' + interval '0 minutes'), ((date_trunc('day', now()) + interval '9 days' + interval '18 hours' + interval '0 minutes') + interval '150 minutes'), 'b2431795-ed35-49ac-a89b-74286bd6feeb', 'arts', 10)
on conflict (id) do nothing;
insert into public.event_tags (event_id, interest_slug) values ('5c641021-17b2-4952-af80-e084f0fc4a61', 'art') on conflict do nothing;
insert into public.event_tags (event_id, interest_slug) values ('5c641021-17b2-4952-af80-e084f0fc4a61', 'social') on conflict do nothing;
insert into public.events (id, title, description, place_id, location_name, address, lat, lng, starts_at, ends_at, creator_id, category_slug, capacity)
values ('fba14fb0-0c96-4a88-a352-b0a1a51d471f', 'Sunset kayak paddle', 'Easy two-mile paddle upstream and back. Rentals available at the ramp; message the organizer if you need one.', 'ca4864c5-2328-449c-a782-1a48653608cd', 'Brightwater Kayak Put-in', null, 39.9532, -83.0166, (date_trunc('day', now()) + interval '10 days' + interval '18 hours' + interval '45 minutes'), ((date_trunc('day', now()) + interval '10 days' + interval '18 hours' + interval '45 minutes') + interval '90 minutes'), '28572a41-206d-4bd8-a853-31ab1a437aea', 'outdoors', 8)
on conflict (id) do nothing;
insert into public.event_tags (event_id, interest_slug) values ('fba14fb0-0c96-4a88-a352-b0a1a51d471f', 'outdoors') on conflict do nothing;
insert into public.event_tags (event_id, interest_slug) values ('fba14fb0-0c96-4a88-a352-b0a1a51d471f', 'date-night') on conflict do nothing;
insert into public.events (id, title, description, place_id, location_name, address, lat, lng, starts_at, ends_at, creator_id, category_slug, capacity)
values ('3d1ba7c4-f13c-4ddb-a9ed-0b72a9bb0419', 'Season opener watch party', 'First game of the season. Back room reserved. (This one already happened.)', 'a383ba25-872d-4154-ae60-51da7901394f', 'Cannon & Crown', '1210 Oak St', 39.9648, -82.9712, (date_trunc('day', now()) + interval '-5 days' + interval '12 hours' + interval '0 minutes'), ((date_trunc('day', now()) + interval '-5 days' + interval '12 hours' + interval '0 minutes') + interval '240 minutes'), '3eb1d493-2346-45eb-ac2f-e4ea355f946a', 'watch-party', 30)
on conflict (id) do nothing;
insert into public.event_tags (event_id, interest_slug) values ('3d1ba7c4-f13c-4ddb-a9ed-0b72a9bb0419', 'sports') on conflict do nothing;
insert into public.event_tags (event_id, interest_slug) values ('3d1ba7c4-f13c-4ddb-a9ed-0b72a9bb0419', 'ohio-state') on conflict do nothing;

-- Attendees (the join trigger blocks past events, so bypass it for historical seed rows)
alter table public.event_attendees disable trigger event_attendees_check_join;
insert into public.event_attendees (event_id, user_id) values ('2194b5a2-2f6c-466a-af4d-cf70d0d11552', '28300d2a-8dcf-4599-a2da-9c4bbcd955da') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('2194b5a2-2f6c-466a-af4d-cf70d0d11552', '3eb1d493-2346-45eb-ac2f-e4ea355f946a') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('2194b5a2-2f6c-466a-af4d-cf70d0d11552', 'f6e4d056-f565-41b4-a2e0-f9347bbf87df') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('2194b5a2-2f6c-466a-af4d-cf70d0d11552', '28572a41-206d-4bd8-a853-31ab1a437aea') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('2194b5a2-2f6c-466a-af4d-cf70d0d11552', '1841f2ef-9435-49e0-ab03-f1e4c6744209') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('78a3b49a-b65b-46e5-aa7a-867722a97ea7', '3eb1d493-2346-45eb-ac2f-e4ea355f946a') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('78a3b49a-b65b-46e5-aa7a-867722a97ea7', '28300d2a-8dcf-4599-a2da-9c4bbcd955da') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('78a3b49a-b65b-46e5-aa7a-867722a97ea7', 'ee4edfe3-9370-441b-a004-14b4bfff0b9d') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('78a3b49a-b65b-46e5-aa7a-867722a97ea7', 'f6e4d056-f565-41b4-a2e0-f9347bbf87df') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('93a5055c-5fb4-4d59-a82e-ac9bec6adced', 'f097e035-c64b-499d-a203-345d923f934d') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('93a5055c-5fb4-4d59-a82e-ac9bec6adced', '28572a41-206d-4bd8-a853-31ab1a437aea') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('93a5055c-5fb4-4d59-a82e-ac9bec6adced', '1841f2ef-9435-49e0-ab03-f1e4c6744209') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('fb21e651-2c8f-40e8-a235-208e45de5816', 'f097e035-c64b-499d-a203-345d923f934d') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('fb21e651-2c8f-40e8-a235-208e45de5816', '28300d2a-8dcf-4599-a2da-9c4bbcd955da') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('0cb78784-f724-4d53-a12b-ff5eeec77fd7', '1841f2ef-9435-49e0-ab03-f1e4c6744209') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('0cb78784-f724-4d53-a12b-ff5eeec77fd7', 'ee4edfe3-9370-441b-a004-14b4bfff0b9d') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('0cb78784-f724-4d53-a12b-ff5eeec77fd7', 'b2431795-ed35-49ac-a89b-74286bd6feeb') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('9df47047-8be5-44da-aa22-3fc0e3fa7980', '1841f2ef-9435-49e0-ab03-f1e4c6744209') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('9df47047-8be5-44da-aa22-3fc0e3fa7980', 'f097e035-c64b-499d-a203-345d923f934d') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('9df47047-8be5-44da-aa22-3fc0e3fa7980', 'b2431795-ed35-49ac-a89b-74286bd6feeb') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('9df47047-8be5-44da-aa22-3fc0e3fa7980', '3eb1d493-2346-45eb-ac2f-e4ea355f946a') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('7a909fa4-dd98-4bfe-a0b8-270abd366a08', '28572a41-206d-4bd8-a853-31ab1a437aea') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('7a909fa4-dd98-4bfe-a0b8-270abd366a08', '28300d2a-8dcf-4599-a2da-9c4bbcd955da') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('7a909fa4-dd98-4bfe-a0b8-270abd366a08', 'ee4edfe3-9370-441b-a004-14b4bfff0b9d') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('0b729311-7709-4f3a-ab0a-d9514f26be75', 'b2431795-ed35-49ac-a89b-74286bd6feeb') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('0b729311-7709-4f3a-ab0a-d9514f26be75', 'f097e035-c64b-499d-a203-345d923f934d') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('0b729311-7709-4f3a-ab0a-d9514f26be75', 'ee4edfe3-9370-441b-a004-14b4bfff0b9d') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('3d0704a2-f478-4819-a88a-20304708d229', 'f6e4d056-f565-41b4-a2e0-f9347bbf87df') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('3d0704a2-f478-4819-a88a-20304708d229', '3eb1d493-2346-45eb-ac2f-e4ea355f946a') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('3d0704a2-f478-4819-a88a-20304708d229', '28300d2a-8dcf-4599-a2da-9c4bbcd955da') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('00bc1dba-cae4-48c9-a594-7ae7738cb2f4', '28572a41-206d-4bd8-a853-31ab1a437aea') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('00bc1dba-cae4-48c9-a594-7ae7738cb2f4', '28300d2a-8dcf-4599-a2da-9c4bbcd955da') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('00bc1dba-cae4-48c9-a594-7ae7738cb2f4', 'f097e035-c64b-499d-a203-345d923f934d') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('00bc1dba-cae4-48c9-a594-7ae7738cb2f4', 'f6e4d056-f565-41b4-a2e0-f9347bbf87df') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('5c641021-17b2-4952-af80-e084f0fc4a61', 'b2431795-ed35-49ac-a89b-74286bd6feeb') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('5c641021-17b2-4952-af80-e084f0fc4a61', 'ee4edfe3-9370-441b-a004-14b4bfff0b9d') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('fba14fb0-0c96-4a88-a352-b0a1a51d471f', '28572a41-206d-4bd8-a853-31ab1a437aea') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('fba14fb0-0c96-4a88-a352-b0a1a51d471f', '1841f2ef-9435-49e0-ab03-f1e4c6744209') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('3d1ba7c4-f13c-4ddb-a9ed-0b72a9bb0419', '3eb1d493-2346-45eb-ac2f-e4ea355f946a') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('3d1ba7c4-f13c-4ddb-a9ed-0b72a9bb0419', 'f6e4d056-f565-41b4-a2e0-f9347bbf87df') on conflict do nothing;
insert into public.event_attendees (event_id, user_id) values ('3d1ba7c4-f13c-4ddb-a9ed-0b72a9bb0419', '28300d2a-8dcf-4599-a2da-9c4bbcd955da') on conflict do nothing;
alter table public.event_attendees enable trigger event_attendees_check_join;

-- Reports (demonstrates both report read paths)
insert into public.reports (reporter_id, target_type, target_id, reason, details, status) values ('28300d2a-8dcf-4599-a2da-9c4bbcd955da', 'place', '243e3950-03d9-4e54-a82f-69906ae98ff2', 'inaccurate', 'They started charging a cover on weekends, so the description is out of date.', 'open') on conflict do nothing;
insert into public.reports (reporter_id, target_type, target_id, reason, details, status) values ('f097e035-c64b-499d-a203-345d923f934d', 'place', '7000030a-8bcf-4a9e-a24a-b771f4bd4a35', 'closed', 'The middle shop shut down last month.', 'open') on conflict do nothing;
insert into public.reports (reporter_id, target_type, target_id, reason, details, status) values ('3eb1d493-2346-45eb-ac2f-e4ea355f946a', 'place', '05693bb3-4b18-4463-aa86-6f0866d70bd7', 'inaccurate', 'Closing time is earlier than listed now.', 'reviewed') on conflict do nothing;

-- Follows
insert into public.follows (follower_id, following_id) values ('28300d2a-8dcf-4599-a2da-9c4bbcd955da', '3eb1d493-2346-45eb-ac2f-e4ea355f946a') on conflict do nothing;
insert into public.follows (follower_id, following_id) values ('28300d2a-8dcf-4599-a2da-9c4bbcd955da', '28572a41-206d-4bd8-a853-31ab1a437aea') on conflict do nothing;
insert into public.follows (follower_id, following_id) values ('28300d2a-8dcf-4599-a2da-9c4bbcd955da', 'f097e035-c64b-499d-a203-345d923f934d') on conflict do nothing;
insert into public.follows (follower_id, following_id) values ('3eb1d493-2346-45eb-ac2f-e4ea355f946a', '28300d2a-8dcf-4599-a2da-9c4bbcd955da') on conflict do nothing;
insert into public.follows (follower_id, following_id) values ('3eb1d493-2346-45eb-ac2f-e4ea355f946a', 'f6e4d056-f565-41b4-a2e0-f9347bbf87df') on conflict do nothing;
insert into public.follows (follower_id, following_id) values ('f097e035-c64b-499d-a203-345d923f934d', 'b2431795-ed35-49ac-a89b-74286bd6feeb') on conflict do nothing;
insert into public.follows (follower_id, following_id) values ('f097e035-c64b-499d-a203-345d923f934d', '28300d2a-8dcf-4599-a2da-9c4bbcd955da') on conflict do nothing;
insert into public.follows (follower_id, following_id) values ('1841f2ef-9435-49e0-ab03-f1e4c6744209', 'f097e035-c64b-499d-a203-345d923f934d') on conflict do nothing;
insert into public.follows (follower_id, following_id) values ('28572a41-206d-4bd8-a853-31ab1a437aea', '28300d2a-8dcf-4599-a2da-9c4bbcd955da') on conflict do nothing;
insert into public.follows (follower_id, following_id) values ('28572a41-206d-4bd8-a853-31ab1a437aea', 'f6e4d056-f565-41b4-a2e0-f9347bbf87df') on conflict do nothing;
insert into public.follows (follower_id, following_id) values ('b2431795-ed35-49ac-a89b-74286bd6feeb', 'ee4edfe3-9370-441b-a004-14b4bfff0b9d') on conflict do nothing;
insert into public.follows (follower_id, following_id) values ('ee4edfe3-9370-441b-a004-14b4bfff0b9d', 'b2431795-ed35-49ac-a89b-74286bd6feeb') on conflict do nothing;
insert into public.follows (follower_id, following_id) values ('ee4edfe3-9370-441b-a004-14b4bfff0b9d', '28300d2a-8dcf-4599-a2da-9c4bbcd955da') on conflict do nothing;
insert into public.follows (follower_id, following_id) values ('f6e4d056-f565-41b4-a2e0-f9347bbf87df', '3eb1d493-2346-45eb-ac2f-e4ea355f946a') on conflict do nothing;
insert into public.follows (follower_id, following_id) values ('f6e4d056-f565-41b4-a2e0-f9347bbf87df', '28572a41-206d-4bd8-a853-31ab1a437aea') on conflict do nothing;
insert into public.follows (follower_id, following_id) values ('b12fb965-a620-40e9-a0a8-8d379dcbbf40', '28300d2a-8dcf-4599-a2da-9c4bbcd955da') on conflict do nothing;
insert into public.follows (follower_id, following_id) values ('b12fb965-a620-40e9-a0a8-8d379dcbbf40', 'ee4edfe3-9370-441b-a004-14b4bfff0b9d') on conflict do nothing;
