/**
 * Fictional demo data for FindMaxxing.
 *
 * Every user, place and event here is invented. Names, tips and descriptions
 * are illustrative only and must not be read as real recommendations.
 * Coordinates sit in real Columbus, Ohio neighborhoods so the map looks alive.
 *
 * This file is the single source of truth for BOTH:
 *   - the demo-mode store (src/lib/data/demo)
 *   - supabase/seed.sql (generated by `npm run seed:sql`)
 */
import { createHash } from "node:crypto";

/** Deterministic UUID-shaped id from a label, so seeds are stable. */
export function stableId(label: string): string {
  const h = createHash("sha256").update(`findmaxxing:${label}`).digest("hex");
  // Format as a v4-looking UUID (variant bits set) so uuid validators accept it.
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-4${h.slice(13, 16)}-a${h.slice(17, 20)}-${h.slice(20, 32)}`;
}

export const DEMO_PASSWORD = "findmaxxing";
export const SEED_CITY = "Columbus";

export interface SeedUser {
  id: string;
  email: string;
  username: string;
  displayName: string;
  bio: string;
  homeCity: string;
  interests: string[];
}

export interface SeedPlace {
  id: string;
  name: string;
  description: string;
  localTip: string;
  categorySlug: string;
  lat: number;
  lng: number;
  address: string | null;
  neighborhood: string;
  city: string;
  creator: string; // username
  tags: string[];
  /** Defaults to "public". "locals" exercises the trust tier. */
  visibility?: "public" | "locals";
}

export interface SeedEvent {
  id: string;
  title: string;
  description: string;
  place: string | null; // seed place name
  locationName: string;
  address: string | null;
  lat: number;
  lng: number;
  /** Days from "now" (may be negative for past events). */
  startsInDays: number;
  startHour: number; // 24h local
  startMinute: number;
  durationMinutes: number | null;
  creator: string; // username
  categorySlug: string;
  capacity: number | null;
  tags: string[];
  attendees: string[]; // usernames
}

export interface SeedRating {
  place: string;
  user: string;
  score: number;
  note: string | null;
}

const u = (username: string) => stableId(`user:${username}`);
const p = (name: string) => stableId(`place:${name}`);
const e = (title: string) => stableId(`event:${title}`);

export const SEED_USERS: SeedUser[] = [
  {
    id: u("maya_r"), email: "maya@example.com", username: "maya_r", displayName: "Maya Reyes",
    bio: "Moved here in June. Collecting pickup games and cheap tacos.",
    homeCity: "Columbus", interests: ["pickup-sports", "food", "cheap-eats", "new-in-town", "running"],
  },
  {
    id: u("theo"), email: "theo@example.com", username: "theo", displayName: "Theo Okafor",
    bio: "Lifelong Columbus. Will argue about the best place to watch the game.",
    homeCity: "Columbus", interests: ["sports", "ohio-state", "nightlife", "social"],
  },
  {
    id: u("jules"), email: "jules@example.com", username: "jules", displayName: "Jules Park",
    bio: "Grad student. Study spots, trails, and the occasional basement show.",
    homeCity: "Columbus", interests: ["studying", "coffee", "hiking", "music", "college"],
  },
  {
    id: u("sam_k"), email: "sam@example.com", username: "sam_k", displayName: "Sam Kowalski",
    bio: "Climber, board game hoarder, disc golf enjoyer.",
    homeCity: "Columbus", interests: ["climbing", "board-games", "outdoors", "gaming"],
  },
  {
    id: u("priya"), email: "priya@example.com", username: "priya", displayName: "Priya Natarajan",
    bio: "Organizes run club Thursdays. Ask me about routes.",
    homeCity: "Columbus", interests: ["running", "fitness", "cycling", "dogs", "social"],
  },
  {
    id: u("dev"), email: "dev@example.com", username: "dev", displayName: "Devin Hale",
    bio: "Printmaker. Community market regular. Knows every mural.",
    homeCity: "Columbus", interests: ["art", "volunteering", "social", "music"],
  },
  {
    id: u("lena"), email: "lena@example.com", username: "lena", displayName: "Lena Fischer",
    bio: "Here for the date spots that don't cost $90 a head.",
    homeCity: "Columbus", interests: ["date-night", "food", "nightlife", "art"],
  },
  {
    id: u("marcus"), email: "marcus@example.com", username: "marcus", displayName: "Marcus Bell",
    bio: "Sand volleyball, pickleball, whatever's got a net.",
    homeCity: "Columbus", interests: ["pickup-sports", "sports", "fitness", "social"],
  },
  {
    // Deliberately not a Columbus local: no home city match and no places
    // contributed here. Locals-only listings stay hidden from this account,
    // which is what makes the trust tier demonstrable in demo mode.
    id: u("nina"), email: "nina@example.com", username: "nina", displayName: "Nina Alvarez",
    bio: "Visiting from Cleveland most weekends. Tell me where to eat.",
    homeCity: "Cleveland", interests: ["food", "coffee", "art", "new-in-town"],
  },
];

export const SEED_PLACES: SeedPlace[] = [
  {
    id: p("Cannon & Crown"), name: "Cannon & Crown", categorySlug: "sports-bar",
    description: "Neighborhood bar with a wall of screens and a crowd that actually cares about the score. Not fancy, not loud outside of game time, and the kitchen stays open late on Saturdays.",
    localTip: "Every Ohio State game plays with sound on the main screen. Get there 45 minutes before kickoff or you're standing.",
    lat: 39.9648, lng: -82.9712, address: "1210 Oak St", neighborhood: "Olde Towne East", city: SEED_CITY,
    creator: "theo", tags: ["sports", "ohio-state", "social"],
  },
  {
    id: p("Tuttle Lot Fields"), name: "Tuttle Lot Fields", categorySlug: "pickup-sports",
    description: "Two full-size grass pitches behind the parking lot. Nets are usually up, lights until 10pm. This is where the regular Sunday pickup happens.",
    localTip: "Sunday 10am pickup is all levels; bring a light and a dark shirt. Weekday evenings are quieter if you want touches.",
    lat: 40.0043, lng: -83.0197, address: null, neighborhood: "University District", city: SEED_CITY,
    creator: "maya_r", tags: ["pickup-sports", "sports", "new-in-town"],
  },
  {
    id: p("Thurman Hollow Courts"), name: "Thurman Hollow Courts", categorySlug: "pickup-sports",
    description: "Two outdoor full courts with decent rims and a resurfaced floor. Runs get competitive after 6pm on weekdays.",
    localTip: "Winners stay. Show up by 5:45 to get in the first game; after 7 it's a long wait.",
    lat: 40.0161, lng: -83.0072, address: null, neighborhood: "Old North", city: SEED_CITY,
    creator: "marcus", tags: ["pickup-sports", "sports"],
  },
  {
    id: p("Ridgeline Loop"), name: "Ridgeline Loop", categorySlug: "outdoors",
    description: "A 3.4-mile loop along the ravine with two real climbs and a river overlook halfway. Mostly dirt, some roots, very runnable.",
    localTip: "Go counter-clockwise so the steep bit is a descent. Sunrise from the overlook is the reason people set alarms.",
    lat: 40.0325, lng: -83.0231, address: null, neighborhood: "Clintonville", city: SEED_CITY,
    creator: "jules", tags: ["hiking", "running", "outdoors", "dogs"], visibility: "locals",
  },
  {
    id: p("Little Alley Dumpling"), name: "Little Alley Dumpling", categorySlug: "food",
    description: "Six-seat counter down an alley off High Street. Hand-folded dumplings, one soup, cash preferred. Owner will remember your order.",
    localTip: "Get the pan-fried pork and the cucumber salad. Twelve dumplings is under ten dollars.",
    lat: 39.9803, lng: -83.0059, address: "Alley behind 900 N High St", neighborhood: "Short North", city: SEED_CITY,
    creator: "maya_r", tags: ["food", "cheap-eats"],
  },
  {
    id: p("The Annex Reading Room"), name: "The Annex Reading Room", categorySlug: "coffee-study",
    description: "The back room of a bookshop that quietly turned into the best study space in the neighborhood. Long tables, outlets at every seat, nobody plays music.",
    localTip: "Buy a coffee, then take the stairs to the mezzanine. Weeknights after 7 it empties out.",
    lat: 39.9575, lng: -83.0215, address: "330 W Broad St", neighborhood: "Franklinton", city: SEED_CITY,
    creator: "jules", tags: ["studying", "coffee", "college"],
  },
  {
    id: p("Boulder & Bramble"), name: "Boulder & Bramble", categorySlug: "fitness",
    description: "Bouldering-only gym in a converted warehouse. Friendly setting crew, resets a wall every week, has a real community night on Wednesdays.",
    localTip: "Wednesday beginner night includes shoes and a 30-minute intro. Go as a stranger, leave with a crew.",
    lat: 39.9812, lng: -83.0412, address: "1550 W 3rd Ave", neighborhood: "Grandview Heights", city: SEED_CITY,
    creator: "sam_k", tags: ["climbing", "fitness", "social"],
  },
  {
    id: p("Brickyard Sunset Steps"), name: "Brickyard Sunset Steps", categorySlug: "date-spot",
    description: "Wide public steps down to the river, facing west. Bring takeout and watch the skyline turn orange. Free, quiet, and somehow never crowded.",
    localTip: "Grab dumplings from Little Alley on the way. Arrive 20 minutes before sunset for the good seats.",
    lat: 39.9596, lng: -83.0108, address: null, neighborhood: "Franklinton", city: SEED_CITY,
    creator: "lena", tags: ["date-night", "cheap-eats", "outdoors"],
  },
  {
    id: p("Meeple Cellar"), name: "Meeple Cellar", categorySlug: "gaming-hobby",
    description: "Basement board game cafe with a library of 600+ games and staff who will teach anything. Table fee is $5, waived if you order food.",
    localTip: "Thursdays are open-table night: sit down at any table with an empty seat and you're in.",
    lat: 39.9452, lng: -83.0008, address: "620 S Front St", neighborhood: "Brewery District", city: SEED_CITY,
    creator: "sam_k", tags: ["board-games", "gaming", "social"],
  },
  {
    id: p("Fourth Street Basement"), name: "Fourth Street Basement", categorySlug: "music",
    description: "DIY venue under a print shop. Local bands, $10 at the door, all ages until 10. Shows are announced on a chalkboard out front and nowhere else.",
    localTip: "Walk by on Tuesdays to read the chalkboard for the weekend lineup. Bring cash and earplugs.",
    lat: 39.9787, lng: -82.9972, address: "45 E 4th Ave", neighborhood: "Italian Village", city: SEED_CITY,
    creator: "dev", tags: ["music", "nightlife", "art"], visibility: "locals",
  },
  {
    id: p("Hollow Oak Print Studio"), name: "Hollow Oak Print Studio", categorySlug: "arts",
    description: "Community screen-printing studio. Open studio hours on weekends, monthly print nights, and a wall of prints from people who learned here.",
    localTip: "Open studio is $15 for the day including ink. Bring your own blank shirts or totes.",
    lat: 39.9770, lng: -82.9955, address: "51 E 4th Ave", neighborhood: "Italian Village", city: SEED_CITY,
    creator: "dev", tags: ["art", "social"],
  },
  {
    id: p("Grange Night Market"), name: "Grange Night Market", categorySlug: "community",
    description: "Second-Friday evening market in a church parking lot: food stalls, vintage, plants, and a local band. Very easy place to talk to strangers.",
    localTip: "The dumpling stand sells out by 7:30. Bring a folding chair for the band.",
    lat: 39.9662, lng: -82.9378, address: "2200 E Main St", neighborhood: "Bexley", city: SEED_CITY,
    creator: "dev", tags: ["social", "food", "new-in-town", "music"],
  },
  {
    id: p("Lantern Bowl"), name: "Lantern Bowl", categorySlug: "nightlife",
    description: "Six lanes of duckpin bowling in the back of a bar. Cheap games, good jukebox, no shoe rental needed.",
    localTip: "Lanes are first-come. Put your name on the clipboard and grab a drink; the wait is usually one round.",
    lat: 39.9748, lng: -83.0041, address: "780 N High St", neighborhood: "Short North", city: SEED_CITY,
    creator: "theo", tags: ["nightlife", "social", "date-night"],
  },
  {
    id: p("Copper Kettle Run Club Corner"), name: "Copper Kettle Run Club Corner", categorySlug: "fitness",
    description: "The coffee shop corner where the Thursday run club meets. 5k and 8k routes, walkers welcome, coffee discount after.",
    localTip: "Meet at 6:20pm for a 6:30 start. The 8k group turns left at the bridge; the 5k group goes right.",
    lat: 40.0215, lng: -83.0165, address: "3200 N High St", neighborhood: "Clintonville", city: SEED_CITY,
    creator: "priya", tags: ["running", "fitness", "social", "coffee"],
  },
  {
    id: p("Sawmill Disc Golf Meadow"), name: "Sawmill Disc Golf Meadow", categorySlug: "outdoors",
    description: "Nine-hole disc golf course through a meadow and a stand of pines. Free, rarely busy on weekday mornings.",
    localTip: "Hole 6 plays over the creek; bring a disc you don't love. Loaner discs at the shed on weekends.",
    lat: 40.0111, lng: -83.0552, address: null, neighborhood: "Upper Arlington", city: SEED_CITY,
    creator: "sam_k", tags: ["outdoors", "social"],
  },
  {
    id: p("Brightwater Kayak Put-in"), name: "Brightwater Kayak Put-in", categorySlug: "outdoors",
    description: "Gravel ramp with easy parking and a calm two-mile paddle downstream to the next take-out. Rentals nearby on weekends.",
    localTip: "Paddle upstream first so the return is easy. Sunset paddles are the move in September.",
    lat: 39.9532, lng: -83.0166, address: null, neighborhood: "Franklinton", city: SEED_CITY,
    creator: "priya", tags: ["outdoors", "date-night"],
  },
  {
    id: p("Buckeye Basement Tacos"), name: "Buckeye Basement Tacos", categorySlug: "food",
    description: "Late-night taco window in the basement of a student building. Three tacos and a drink for $8, open until 2am on weekends.",
    localTip: "The al pastor runs out by 1am. The line moves fast; the salsa verde does not mess around.",
    lat: 39.9968, lng: -83.0075, address: "1800 N High St", neighborhood: "University District", city: SEED_CITY,
    creator: "maya_r", tags: ["food", "cheap-eats", "college", "nightlife"],
  },
  {
    id: p("Nightowl Study Lounge"), name: "Nightowl Study Lounge", categorySlug: "coffee-study",
    description: "24-hour lounge with booths, whiteboards and a vending wall. Free with a student ID, $3 a day otherwise.",
    localTip: "The corner booths have the only good outlets. After midnight it's dead quiet.",
    lat: 39.9992, lng: -83.0121, address: "1990 N High St", neighborhood: "University District", city: SEED_CITY,
    creator: "jules", tags: ["studying", "college", "coffee"],
  },
  {
    id: p("Riverbend Volleyball Pits"), name: "Riverbend Volleyball Pits", categorySlug: "pickup-sports",
    description: "Four sand courts by the river with lights until 11. Open play most evenings; leagues take the far two courts on Tuesdays.",
    localTip: "Courts 1 and 2 are always open play. Bring your own ball and a towel; the sand gets everywhere.",
    lat: 39.9868, lng: -83.0381, address: null, neighborhood: "Grandview Heights", city: SEED_CITY,
    creator: "marcus", tags: ["pickup-sports", "sports", "social"],
  },
  {
    id: p("Merion Rec Pickleball"), name: "Merion Rec Pickleball", categorySlug: "pickup-sports",
    description: "Six courts at a small rec center. Open play mornings, ladder nights on Mondays, loaner paddles at the desk.",
    localTip: "Open play 8-11am is beginner friendly. Monday ladder night is where the good players are.",
    lat: 39.9401, lng: -82.9931, address: "1100 Parsons Ave", neighborhood: "Merion Village", city: SEED_CITY,
    creator: "marcus", tags: ["pickup-sports", "sports", "fitness"],
  },
  {
    id: p("Cobblestone Chess Corner"), name: "Cobblestone Chess Corner", categorySlug: "gaming-hobby",
    description: "Four stone chess tables under a big sycamore. Regulars most afternoons, casual games, blitz on Saturdays.",
    localTip: "Bring a clock and someone will play you. Saturday blitz starts around 2.",
    lat: 39.9735, lng: -83.0027, address: null, neighborhood: "Victorian Village", city: SEED_CITY,
    creator: "sam_k", tags: ["board-games", "social", "gaming"],
  },
  {
    id: p("Wren Street Wine Porch"), name: "Wren Street Wine Porch", categorySlug: "date-spot",
    description: "Tiny wine bar with a wraparound porch and $8 glasses. String lights, a record player, and a two-hour table limit nobody enforces.",
    localTip: "The porch is first-come; Tuesdays and Wednesdays you can always get a spot. Cheese board is big enough for two.",
    lat: 39.9483, lng: -82.9902, address: "215 Thurman Ave", neighborhood: "German Village", city: SEED_CITY,
    creator: "lena", tags: ["date-night", "nightlife"],
  },
  {
    id: p("The Lumen Rooftop"), name: "The Lumen Rooftop", categorySlug: "nightlife",
    description: "Hotel rooftop that lets non-guests up. No cover, decent view of the skyline, cocktails are fine and the sunset is not.",
    localTip: "Go on a weeknight at 8; weekends have a line. Take the elevator to 12 then the stairs.",
    lat: 39.9622, lng: -82.9993, address: "70 E Gay St", neighborhood: "Downtown", city: SEED_CITY,
    creator: "lena", tags: ["nightlife", "date-night"],
  },
  {
    id: p("Northend Thrift Alley"), name: "Northend Thrift Alley", categorySlug: "other",
    description: "Three thrift shops in a row on one block, plus a record store. Good for furnishing a first apartment on a budget.",
    localTip: "The middle shop restocks Wednesday mornings. Furniture goes fast.",
    lat: 40.0256, lng: -83.0148, address: "3400 N High St", neighborhood: "Clintonville", city: SEED_CITY,
    creator: "maya_r", tags: ["new-in-town", "cheap-eats"],
  },
  {
    id: p("Overpass Skate Bowl"), name: "Overpass Skate Bowl", categorySlug: "outdoors",
    description: "Concrete bowl and a small street section under the highway. Covered, so it works in the rain. Friendly to beginners before noon.",
    localTip: "Mornings are quiet and forgiving. Bring water; there's no fountain.",
    lat: 39.9553, lng: -83.0055, address: null, neighborhood: "Franklinton", city: SEED_CITY,
    creator: "dev", tags: ["outdoors", "fitness"],
  },
  {
    id: p("Hilltop Kickabout"), name: "Hilltop Kickabout", categorySlug: "pickup-sports",
    description: "Small-sided pitch behind a community center. Wednesday evening 7v7 is a fixture; very mixed levels, very friendly.",
    localTip: "Wednesday 6:30pm. Someone always brings pinnies. Say hi to whoever has the ball bag.",
    lat: 39.9622, lng: -83.0648, address: "2600 W Broad St", neighborhood: "Hilltop", city: SEED_CITY,
    creator: "theo", tags: ["pickup-sports", "sports", "new-in-town"],
  },
];

export const SEED_EVENTS: SeedEvent[] = [
  {
    id: e("Sunday pickup soccer"), title: "Sunday pickup soccer", categorySlug: "pickup-sports",
    description: "Weekly all-levels pickup. We play 11v11 if numbers allow, otherwise split into two small-sided games. Bring a light and a dark shirt, water, and turf or cleats.",
    place: "Tuttle Lot Fields", locationName: "Tuttle Lot Fields", address: null, lat: 40.0043, lng: -83.0197,
    startsInDays: 2, startHour: 10, startMinute: 0, durationMinutes: 120, creator: "maya_r", capacity: 24,
    tags: ["pickup-sports", "sports", "new-in-town"], attendees: ["maya_r", "theo", "marcus", "priya", "sam_k"],
  },
  {
    id: e("OSU game watch party"), title: "OSU game watch party", categorySlug: "watch-party",
    description: "Big screen, sound on, tables reserved in the back for the FindMaxxing crew. Wear scarlet. Kitchen open the whole game.",
    place: "Cannon & Crown", locationName: "Cannon & Crown", address: "1210 Oak St", lat: 39.9648, lng: -82.9712,
    startsInDays: 5, startHour: 15, startMinute: 30, durationMinutes: 240, creator: "theo", capacity: 30,
    tags: ["sports", "ohio-state", "social"], attendees: ["theo", "maya_r", "lena", "marcus"],
  },
  {
    id: e("Ridgeline sunrise hike"), title: "Ridgeline sunrise hike", categorySlug: "outdoors",
    description: "Counter-clockwise loop, easy pace, coffee at the overlook. Headlamp for the first 20 minutes. Dogs on leash welcome.",
    place: "Ridgeline Loop", locationName: "Ridgeline Loop trailhead", address: null, lat: 40.0325, lng: -83.0231,
    startsInDays: 3, startHour: 6, startMinute: 45, durationMinutes: 90, creator: "jules", capacity: null,
    tags: ["hiking", "outdoors", "dogs"], attendees: ["jules", "priya", "sam_k"],
  },
  {
    id: e("Midterms study block"), title: "Midterms study block", categorySlug: "coffee-study",
    description: "Silent focus blocks (50 on / 10 off) on the mezzanine. Any subject. Bring headphones; we'll grab the long table.",
    place: "The Annex Reading Room", locationName: "The Annex Reading Room", address: "330 W Broad St", lat: 39.9575, lng: -83.0215,
    startsInDays: 1, startHour: 18, startMinute: 0, durationMinutes: 180, creator: "jules", capacity: 12,
    tags: ["studying", "college"], attendees: ["jules", "maya_r"],
  },
  {
    id: e("Beginner climbing night"), title: "Beginner climbing night", categorySlug: "fitness",
    description: "Never climbed? Perfect. Intro to bouldering, shoes included, then we climb together. Meet by the front desk.",
    place: "Boulder & Bramble", locationName: "Boulder & Bramble", address: "1550 W 3rd Ave", lat: 39.9812, lng: -83.0412,
    startsInDays: 4, startHour: 19, startMinute: 0, durationMinutes: 120, creator: "sam_k", capacity: 12,
    tags: ["climbing", "fitness", "social", "new-in-town"], attendees: ["sam_k", "lena", "dev"],
  },
  {
    id: e("Open-table board game night"), title: "Open-table board game night", categorySlug: "gaming-hobby",
    description: "Sit anywhere with an empty seat. We'll have Catan, Wingspan, Codenames and whatever the staff wants to teach.",
    place: "Meeple Cellar", locationName: "Meeple Cellar", address: "620 S Front St", lat: 39.9452, lng: -83.0008,
    startsInDays: 2, startHour: 19, startMinute: 0, durationMinutes: 180, creator: "sam_k", capacity: 16,
    tags: ["board-games", "gaming", "social"], attendees: ["sam_k", "jules", "dev", "theo"],
  },
  {
    id: e("Newcomers coffee walk"), title: "Newcomers coffee walk", categorySlug: "community",
    description: "Slow walk through the Short North with coffee stops. Made for people who moved here in the last year. Zero agenda, just faces.",
    place: null, locationName: "Short North arch at Goodale", address: "N High St & Goodale St", lat: 39.9738, lng: -83.0043,
    startsInDays: 6, startHour: 10, startMinute: 0, durationMinutes: 90, creator: "priya", capacity: null,
    tags: ["new-in-town", "social", "coffee"], attendees: ["priya", "maya_r", "lena"],
  },
  {
    id: e("Basement show: three local bands"), title: "Basement show: three local bands", categorySlug: "music",
    description: "$10 at the door, all ages until 10pm. Lineup on the chalkboard. Earplugs at the merch table.",
    place: "Fourth Street Basement", locationName: "Fourth Street Basement", address: "45 E 4th Ave", lat: 39.9787, lng: -82.9972,
    startsInDays: 7, startHour: 21, startMinute: 0, durationMinutes: 180, creator: "dev", capacity: 80,
    tags: ["music", "nightlife"], attendees: ["dev", "jules", "lena"],
  },
  {
    id: e("3v3 basketball run"), title: "3v3 basketball run", categorySlug: "pickup-sports",
    description: "Half-court 3s, games to 15, winners stay. Bring a ball if you have one.",
    place: "Thurman Hollow Courts", locationName: "Thurman Hollow Courts", address: null, lat: 40.0161, lng: -83.0072,
    startsInDays: 1, startHour: 18, startMinute: 0, durationMinutes: 120, creator: "marcus", capacity: 12,
    tags: ["pickup-sports", "sports"], attendees: ["marcus", "theo", "maya_r"],
  },
  {
    id: e("Thursday run club"), title: "Thursday run club", categorySlug: "fitness",
    description: "5k and 8k routes from the corner. All paces, nobody gets dropped. Coffee discount after with the club sticker.",
    place: "Copper Kettle Run Club Corner", locationName: "Copper Kettle Run Club Corner", address: "3200 N High St", lat: 40.0215, lng: -83.0165,
    startsInDays: 3, startHour: 18, startMinute: 30, durationMinutes: 75, creator: "priya", capacity: null,
    tags: ["running", "fitness", "social"], attendees: ["priya", "maya_r", "jules", "marcus"],
  },
  {
    id: e("Print night: screen-print a tote"), title: "Print night: screen-print a tote", categorySlug: "arts",
    description: "Learn to pull a screen and leave with a tote. Materials included. Beginners very welcome.",
    place: "Hollow Oak Print Studio", locationName: "Hollow Oak Print Studio", address: "51 E 4th Ave", lat: 39.9770, lng: -82.9955,
    startsInDays: 9, startHour: 18, startMinute: 0, durationMinutes: 150, creator: "dev", capacity: 10,
    tags: ["art", "social"], attendees: ["dev", "lena"],
  },
  {
    id: e("Sunset kayak paddle"), title: "Sunset kayak paddle", categorySlug: "outdoors",
    description: "Easy two-mile paddle upstream and back. Rentals available at the ramp; message the organizer if you need one.",
    place: "Brightwater Kayak Put-in", locationName: "Brightwater Kayak Put-in", address: null, lat: 39.9532, lng: -83.0166,
    startsInDays: 10, startHour: 18, startMinute: 45, durationMinutes: 90, creator: "priya", capacity: 8,
    tags: ["outdoors", "date-night"], attendees: ["priya", "sam_k"],
  },
  {
    id: e("Season opener watch party"), title: "Season opener watch party", categorySlug: "watch-party",
    description: "First game of the season. Back room reserved. (This one already happened.)",
    place: "Cannon & Crown", locationName: "Cannon & Crown", address: "1210 Oak St", lat: 39.9648, lng: -82.9712,
    startsInDays: -5, startHour: 12, startMinute: 0, durationMinutes: 240, creator: "theo", capacity: 30,
    tags: ["sports", "ohio-state"], attendees: ["theo", "marcus", "maya_r"],
  },
];

export const SEED_RATINGS: SeedRating[] = [
  { place: "Cannon & Crown", user: "theo", score: 5, note: "The only bar that turns the sound on." },
  { place: "Cannon & Crown", user: "maya_r", score: 4, note: null },
  { place: "Cannon & Crown", user: "marcus", score: 5, note: "Wings are underrated." },
  { place: "Tuttle Lot Fields", user: "maya_r", score: 5, note: "Made friends here in my first week." },
  { place: "Tuttle Lot Fields", user: "marcus", score: 4, note: null },
  { place: "Tuttle Lot Fields", user: "theo", score: 4, note: null },
  { place: "Thurman Hollow Courts", user: "marcus", score: 4, note: "Good runs, long waits." },
  { place: "Thurman Hollow Courts", user: "theo", score: 4, note: null },
  { place: "Ridgeline Loop", user: "jules", score: 5, note: "The overlook at sunrise is unreal." },
  { place: "Ridgeline Loop", user: "priya", score: 5, note: "Best trail run in the city." },
  { place: "Ridgeline Loop", user: "sam_k", score: 4, note: null },
  { place: "Little Alley Dumpling", user: "maya_r", score: 5, note: "Cheapest great meal I've found." },
  { place: "Little Alley Dumpling", user: "lena", score: 5, note: null },
  { place: "Little Alley Dumpling", user: "jules", score: 4, note: null },
  { place: "The Annex Reading Room", user: "jules", score: 5, note: "Wrote my whole thesis here." },
  { place: "The Annex Reading Room", user: "maya_r", score: 4, note: null },
  { place: "Boulder & Bramble", user: "sam_k", score: 5, note: null },
  { place: "Boulder & Bramble", user: "lena", score: 4, note: "Beginner night was so welcoming." },
  { place: "Brickyard Sunset Steps", user: "lena", score: 5, note: "Free date night, every time." },
  { place: "Brickyard Sunset Steps", user: "priya", score: 4, note: null },
  { place: "Meeple Cellar", user: "sam_k", score: 5, note: null },
  { place: "Meeple Cellar", user: "dev", score: 4, note: null },
  { place: "Meeple Cellar", user: "theo", score: 4, note: null },
  { place: "Fourth Street Basement", user: "dev", score: 5, note: null },
  { place: "Fourth Street Basement", user: "jules", score: 4, note: "Loud in the best way." },
  { place: "Hollow Oak Print Studio", user: "dev", score: 5, note: null },
  { place: "Grange Night Market", user: "dev", score: 4, note: null },
  { place: "Grange Night Market", user: "maya_r", score: 5, note: "Talked to more people here than in a month." },
  { place: "Lantern Bowl", user: "theo", score: 4, note: null },
  { place: "Lantern Bowl", user: "lena", score: 4, note: null },
  { place: "Copper Kettle Run Club Corner", user: "priya", score: 5, note: null },
  { place: "Copper Kettle Run Club Corner", user: "maya_r", score: 5, note: null },
  { place: "Sawmill Disc Golf Meadow", user: "sam_k", score: 4, note: null },
  { place: "Brightwater Kayak Put-in", user: "priya", score: 4, note: null },
  { place: "Buckeye Basement Tacos", user: "maya_r", score: 4, note: null },
  { place: "Buckeye Basement Tacos", user: "jules", score: 5, note: "2am lifesaver." },
  { place: "Nightowl Study Lounge", user: "jules", score: 4, note: null },
  { place: "Riverbend Volleyball Pits", user: "marcus", score: 5, note: null },
  { place: "Riverbend Volleyball Pits", user: "priya", score: 4, note: null },
  { place: "Merion Rec Pickleball", user: "marcus", score: 4, note: null },
  { place: "Cobblestone Chess Corner", user: "sam_k", score: 4, note: null },
  { place: "Wren Street Wine Porch", user: "lena", score: 5, note: "Porch + record player = yes." },
  { place: "Wren Street Wine Porch", user: "theo", score: 4, note: null },
  { place: "The Lumen Rooftop", user: "lena", score: 3, note: "View good, drinks fine." },
  { place: "Northend Thrift Alley", user: "maya_r", score: 4, note: null },
  { place: "Overpass Skate Bowl", user: "dev", score: 4, note: null },
  { place: "Hilltop Kickabout", user: "theo", score: 4, note: null },
  { place: "Hilltop Kickabout", user: "maya_r", score: 5, note: null },
];

export const SEED_SAVES: { user: string; place: string }[] = [
  { user: "maya_r", place: "Cannon & Crown" },
  { user: "maya_r", place: "Ridgeline Loop" },
  { user: "maya_r", place: "Meeple Cellar" },
  { user: "maya_r", place: "Boulder & Bramble" },
  { user: "theo", place: "Little Alley Dumpling" },
  { user: "theo", place: "Meeple Cellar" },
  { user: "jules", place: "Ridgeline Loop" },
  { user: "jules", place: "Little Alley Dumpling" },
  { user: "jules", place: "Fourth Street Basement" },
  { user: "sam_k", place: "Ridgeline Loop" },
  { user: "sam_k", place: "Cobblestone Chess Corner" },
  { user: "priya", place: "Brightwater Kayak Put-in" },
  { user: "priya", place: "Ridgeline Loop" },
  { user: "dev", place: "Grange Night Market" },
  { user: "lena", place: "Brickyard Sunset Steps" },
  { user: "lena", place: "Little Alley Dumpling" },
  { user: "marcus", place: "Tuttle Lot Fields" },
  { user: "marcus", place: "Thurman Hollow Courts" },
];

export interface SeedReport {
  reporter: string;
  targetKind: "place" | "event";
  target: string;
  reason: "inaccurate" | "closed" | "inappropriate" | "spam" | "duplicate" | "other";
  details: string | null;
  status: "open" | "reviewed" | "dismissed";
}

export const SEED_REPORTS: SeedReport[] = [
  {
    reporter: "maya_r", targetKind: "place", target: "The Lumen Rooftop", reason: "inaccurate",
    details: "They started charging a cover on weekends, so the description is out of date.", status: "open",
  },
  {
    reporter: "jules", targetKind: "place", target: "Northend Thrift Alley", reason: "closed",
    details: "The middle shop shut down last month.", status: "open",
  },
  {
    reporter: "theo", targetKind: "place", target: "Buckeye Basement Tacos", reason: "inaccurate",
    details: "Closing time is earlier than listed now.", status: "reviewed",
  },
];

export const SEED_FOLLOWS: { follower: string; following: string }[] = [
  { follower: "maya_r", following: "theo" },
  { follower: "maya_r", following: "priya" },
  { follower: "maya_r", following: "jules" },
  { follower: "theo", following: "maya_r" },
  { follower: "theo", following: "marcus" },
  { follower: "jules", following: "dev" },
  { follower: "jules", following: "maya_r" },
  { follower: "sam_k", following: "jules" },
  { follower: "priya", following: "maya_r" },
  { follower: "priya", following: "marcus" },
  { follower: "dev", following: "lena" },
  { follower: "lena", following: "dev" },
  { follower: "lena", following: "maya_r" },
  { follower: "marcus", following: "theo" },
  { follower: "marcus", following: "priya" },
  { follower: "nina", following: "maya_r" },
  { follower: "nina", following: "lena" },
];

export function seedUserByName(username: string): SeedUser {
  const found = SEED_USERS.find((x) => x.username === username);
  if (!found) throw new Error(`Unknown seed user ${username}`);
  return found;
}
export function seedPlaceByName(name: string): SeedPlace {
  const found = SEED_PLACES.find((x) => x.name === name);
  if (!found) throw new Error(`Unknown seed place ${name}`);
  return found;
}

/** Resolve a seed event's start/end as absolute Dates relative to `now`. */
export function seedEventTimes(ev: SeedEvent, now = new Date()): { startsAt: Date; endsAt: Date | null } {
  const start = new Date(now.getFullYear(), now.getMonth(), now.getDate() + ev.startsInDays, ev.startHour, ev.startMinute, 0, 0);
  const end = ev.durationMinutes ? new Date(start.getTime() + ev.durationMinutes * 60_000) : null;
  return { startsAt: start, endsAt: end };
}
