/**
 * Generates supabase/seed.sql from src/lib/seed/seed-data.ts and taxonomy.
 * Run: npm run seed:sql
 *
 * The output is idempotent-ish (ON CONFLICT DO NOTHING) and creates demo
 * auth users with the shared password from seed-data (demo only!).
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { CATEGORIES, INTERESTS } from "../src/lib/data/taxonomy";
import {
  DEMO_PASSWORD,
  SEED_EVENTS,
  SEED_FOLLOWS,
  SEED_PLACES,
  SEED_RATINGS,
  SEED_REPORTS,
  SEED_SAVES,
  SEED_USERS,
  seedPlaceByName,
  seedUserByName,
} from "../src/lib/seed/seed-data";

const q = (v: string | null | undefined) => (v == null ? "null" : `'${v.replace(/'/g, "''")}'`);
const n = (v: number | null | undefined) => (v == null ? "null" : String(v));

export function buildSeedSql(): string {
  const out: string[] = [];
  out.push(`-- ============================================================================
-- FindMaxxing demo seed. GENERATED by scripts/generate-seed-sql.ts — do not edit.
-- All people, places and events are fictional. Demo password: "${DEMO_PASSWORD}".
-- ============================================================================
`);

  out.push("-- Vocabulary");
  out.push("insert into public.categories (slug, label, emoji, color, scope, sort_order) values");
  out.push(CATEGORIES.map((c, i) => `  (${q(c.slug)}, ${q(c.label)}, ${q(c.emoji)}, ${q(c.color)}, ${q(c.scope)}, ${i})`).join(",\n") + "\non conflict (slug) do update set label = excluded.label, emoji = excluded.emoji, color = excluded.color, scope = excluded.scope, sort_order = excluded.sort_order;\n");
  out.push("insert into public.interests (slug, label, emoji, sort_order) values");
  out.push(INTERESTS.map((c, i) => `  (${q(c.slug)}, ${q(c.label)}, ${q(c.emoji)}, ${i})`).join(",\n") + "\non conflict (slug) do update set label = excluded.label, emoji = excluded.emoji, sort_order = excluded.sort_order;\n");

  out.push("-- Demo auth users (the profiles trigger creates matching profile rows)");
  for (const u of SEED_USERS) {
    out.push(`insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at)
values (${q(u.id)}, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', ${q(u.email)}, crypt(${q(DEMO_PASSWORD)}, gen_salt('bf')), now(), '{"provider":"email","providers":["email"]}', ${q(JSON.stringify({ username: u.username, display_name: u.displayName }))}, now(), now())
on conflict (id) do nothing;`);
  }
  out.push("");
  out.push("-- Profile details");
  for (const u of SEED_USERS) {
    out.push(`update public.profiles set bio = ${q(u.bio)}, home_city = ${q(u.homeCity)}, display_name = ${q(u.displayName)}, username = ${q(u.username)} where id = ${q(u.id)};`);
    for (const i of u.interests) {
      out.push(`insert into public.profile_interests (profile_id, interest_slug) values (${q(u.id)}, ${q(i)}) on conflict do nothing;`);
    }
  }
  out.push("");
  out.push("-- Places");
  for (const p of SEED_PLACES) {
    out.push(`insert into public.places (id, name, description, local_tip, category_slug, lat, lng, address, neighborhood, city, creator_id, visibility)
values (${q(p.id)}, ${q(p.name)}, ${q(p.description)}, ${q(p.localTip)}, ${q(p.categorySlug)}, ${p.lat}, ${p.lng}, ${q(p.address)}, ${q(p.neighborhood)}, ${q(p.city)}, ${q(seedUserByName(p.creator).id)}, ${q(p.visibility ?? "public")})
on conflict (id) do nothing;`);
    for (const t of p.tags) out.push(`insert into public.place_tags (place_id, interest_slug) values (${q(p.id)}, ${q(t)}) on conflict do nothing;`);
  }
  out.push("");
  out.push("-- Ratings (aggregates are recomputed by trigger)");
  for (const r of SEED_RATINGS) {
    out.push(`insert into public.place_ratings (place_id, user_id, score, note) values (${q(seedPlaceByName(r.place).id)}, ${q(seedUserByName(r.user).id)}, ${r.score}, ${q(r.note)}) on conflict (place_id, user_id) do update set score = excluded.score, note = excluded.note;`);
  }
  out.push("");
  out.push("-- Saved places");
  for (const s of SEED_SAVES) {
    out.push(`insert into public.saved_places (user_id, place_id) values (${q(seedUserByName(s.user).id)}, ${q(seedPlaceByName(s.place).id)}) on conflict do nothing;`);
  }
  out.push("");
  out.push("-- Events (times are relative to seed time so the demo always has upcoming events)");
  for (const e of SEED_EVENTS) {
    const start = `(date_trunc('day', now()) + interval '${e.startsInDays} days' + interval '${e.startHour} hours' + interval '${e.startMinute} minutes')`;
    const end = e.durationMinutes ? `(${start} + interval '${e.durationMinutes} minutes')` : "null";
    out.push(`insert into public.events (id, title, description, place_id, location_name, address, lat, lng, starts_at, ends_at, creator_id, category_slug, capacity)
values (${q(e.id)}, ${q(e.title)}, ${q(e.description)}, ${e.place ? q(seedPlaceByName(e.place).id) : "null"}, ${q(e.locationName)}, ${q(e.address)}, ${e.lat}, ${e.lng}, ${start}, ${end}, ${q(seedUserByName(e.creator).id)}, ${q(e.categorySlug)}, ${n(e.capacity)})
on conflict (id) do nothing;`);
    for (const t of e.tags) out.push(`insert into public.event_tags (event_id, interest_slug) values (${q(e.id)}, ${q(t)}) on conflict do nothing;`);
  }
  out.push("");
  out.push("-- Attendees (the join trigger blocks past events, so bypass it for historical seed rows)");
  out.push("alter table public.event_attendees disable trigger event_attendees_check_join;");
  for (const e of SEED_EVENTS) {
    for (const a of e.attendees) {
      out.push(`insert into public.event_attendees (event_id, user_id) values (${q(e.id)}, ${q(seedUserByName(a).id)}) on conflict do nothing;`);
    }
  }
  out.push("alter table public.event_attendees enable trigger event_attendees_check_join;");
  out.push("");
  out.push("-- Reports (demonstrates both report read paths)");
  for (const r of SEED_REPORTS) {
    const target = r.targetKind === "place" ? seedPlaceByName(r.target).id : r.target;
    out.push(`insert into public.reports (reporter_id, target_type, target_id, reason, details, status) values (${q(seedUserByName(r.reporter).id)}, ${q(r.targetKind)}, ${q(target)}, ${q(r.reason)}, ${q(r.details)}, ${q(r.status)}) on conflict do nothing;`);
  }
  out.push("");
  out.push("-- Follows");
  for (const f of SEED_FOLLOWS) {
    out.push(`insert into public.follows (follower_id, following_id) values (${q(seedUserByName(f.follower).id)}, ${q(seedUserByName(f.following).id)}) on conflict do nothing;`);
  }
  out.push("");
  return out.join("\n");
}

if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(__filename)) {
  const target = path.join(process.cwd(), "supabase", "seed.sql");
  writeFileSync(target, buildSeedSql());
  console.log(`Wrote ${target}`);
}
